// src/services/projectModelsService.ts
//
// Business logic behind the staff-triggered "Create Model" flow: validate a
// 3–4 photo selection, record the generation request, and enqueue the worker
// job that talks to Meshy (docs/meshy-integration-implementation-prompt.md).
//
// This service is ADDITIVE. It never touches the capture pipeline, finalize, or
// the reconstruction engine — a Meshy generation is a separate, human-triggered
// job type running BESIDE the in-house path, which stays the fallback.
//
// Returns typed result unions the route maps to HTTP (no Express types here),
// per the AGENTS.md routes → services → models layering.
import { randomUUID } from 'node:crypto';
import { Types } from 'mongoose';
import { Project } from '@/models/Project';
import { Job, MESHY_MODEL_GENERATION_JOB_TYPE, MODEL_OPTIMIZATION_JOB_TYPE } from '@/models/Job';
import { ProjectModel, type IProjectModel } from '@/models/ProjectModel';
import type {
  ModelGenerationTrace,
  ModelProgressPhase,
  ModelSource,
  ModelStatus,
} from '@/models/types/projectModel.types';
import type { UserRole } from '@/models/User';
import {
  findExportableJob,
  findModelSourceJobById,
  isContainedRelativeKey,
  MODEL_INPUT_KEY_PREFIX,
} from '@/services/adminProjectsService';
import { getObjectBytes, headObject, presignObjectPutUrl } from '@/services/s3ObjectStore';
import { BUCKET_ARTIFACTS } from '@/config/s3';
import { env } from '@/config/env';

/**
 * Meshy Multi-Image to 3D accepts 1–4 images. We require a MINIMUM of 3: with
 * fewer views the generative model hallucinates most of the object, and the
 * result is not worth a paid generation. Enforced identically on the client
 * (the Create Model CTA) — this is the authority.
 */
export const MIN_SELECTED_PHOTOS = 3;
export const MAX_SELECTED_PHOTOS = 4;

/** The staff actor requesting or approving a generation. */
export interface ModelActor {
  userId: string;
  role: UserRole;
}

// ── DTOs ─────────────────────────────────────────────────────────────────────

/** Staff-facing model record. Ids are exposed as `id`, never `_id`. */
export interface ProjectModelDto {
  id: string;
  projectId: string;
  jobId: string;
  source: ModelSource;
  status: ModelStatus;
  selectedKeys: string[];
  /**
   * Live worker sub-status for a PROCESSING record — drives the staff progress
   * UI ("Generating 3D model · 45%"). Absent on terminal records and on records
   * written before this field existed, so clients must treat it as optional.
   */
  progress?: { phase: ModelProgressPhase; percent: number };
  artifacts?: { glb: string; usdz?: string; preview?: string };
  approved?: { at: string };
  error?: { code: string; message: string };
  /**
   * How this generation was DECIDED — the synchronous request steps and the
   * photo selector's counters. Absent on every record written before the trace
   * existed, so clients must default it to nothing.
   *
   * STAFF-ONLY: it names our S3 key layout and our pipeline internals. It is on
   * this DTO and deliberately on NEITHER owner DTO.
   */
  generationTrace?: ModelGenerationTrace;
  /**
   * Size of the GLB in bytes, when known. ABSENT MEANS UNKNOWN, NOT SMALL —
   * records predating the field have none until the list backfills them, and a
   * client must render "size unknown", never "0 B".
   */
  glbBytes?: number;
  /** Set on an OPT record: the model it was derived from. */
  optimizedFromId?: string;
  /** Set on an OPT record: what the pass achieved, for the "−68%" label. */
  optimization?: { sourceBytes: number; outputBytes: number };
  /**
   * THE SERVER'S OWN VERDICT on whether the Optimize button belongs on this
   * row. Shipped as a boolean rather than shipping the threshold, because the
   * moment the client re-implements the rule the two can disagree — and the
   * disagreement is invisible until someone taps a button the server refuses.
   * See {@link canOptimizeModel} for the rule itself.
   */
  canOptimize: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * OWNER-facing model. Deliberately smaller than the staff DTO: the URL, the
 * origin flag that drives the "Created by Meshy AI" badge, and whether it is
 * approved — nothing else. No S3 keys, no selectedKeys, no staff actor ids, no
 * meshyTaskId: an owner must not learn our key layout or who curated their
 * project.
 */
export interface OwnerModelDto {
  id: string;
  source: ModelSource;
  glbUrl: string;
  usdzUrl?: string;
  previewUrl?: string;
  approved: boolean;
  /**
   * True when the worker generated this itself after the capture finished,
   * with no human in the loop. Drives the "AI generated — preview quality"
   * badge and the regenerate affordance: an auto-generated model is shown as a
   * preview, not as a finished, signed-off product.
   */
  isAutoGenerated: boolean;
  /**
   * GLB size in bytes when known — absent means UNKNOWN. Named `sizeBytes`
   * rather than `glbBytes`: an owner is told how big their download is, not
   * which of our artifacts it happens to be.
   */
  sizeBytes?: number;
  /** True when this model IS the optimized derivative of another one. */
  isOptimized: boolean;
  /** The server's verdict on the owner-facing Optimize action. */
  canOptimize: boolean;
  createdAt: string;
}

/**
 * One row of the OWNER-facing model list (`GET /projects/:id/models`).
 *
 * A superset of {@link OwnerModelDto} in exactly two respects, and a subset of
 * the staff DTO in every other:
 *
 *  • `status` is present, and `glbUrl` is OPTIONAL as a direct consequence.
 *    {@link OwnerModelDto} describes the one finished model behind
 *    `GET /projects/:id`, so it can promise a URL. A LIST cannot: the row the
 *    owner most needs to see right after tapping Optimize is the QUEUED one,
 *    which has no artifacts yet. Dropping unfinished records would make the
 *    action look like it did nothing.
 *  • `progressPercent` and `error` are carried in the SAME owner-safe shapes
 *    {@link OwnerGenerationDto} already ships — a bare number (never a phase
 *    name, which describes our pipeline internals) and mapped failure copy.
 *
 * Everything staff-only stays out, and the omissions are the point: no
 * `selectedKeys`, no `generationTrace`, no `jobId`/`projectId`, no
 * `optimizedFromId` (it names a record the owner cannot address), no
 * `optimization` before/after byte counts, no actor ids, no S3 keys.
 */
export interface OwnerModelListItemDto {
  id: string;
  source: ModelSource;
  status: ModelStatus;
  /** Present only once the record has artifacts — i.e. once it SUCCEEDED. */
  glbUrl?: string;
  usdzUrl?: string;
  previewUrl?: string;
  approved: boolean;
  isAutoGenerated: boolean;
  sizeBytes?: number;
  isOptimized: boolean;
  canOptimize: boolean;
  /** Coarse 0–100 while pending, when the worker has reported any. */
  progressPercent?: number;
  /** Owner-safe failure copy — mapped codes only, never raw upstream text. */
  error?: { code: string; message: string };
  createdAt: string;
}

/**
 * A generation the owner is currently WAITING on — the state that only exists
 * because generation can now start without anyone asking for it.
 *
 * Deliberately separate from {@link OwnerModelDto}: a project can have a good
 * model AND a newer generation in flight at the same time, and the owner must
 * keep seeing the former while the latter runs.
 */
export interface OwnerGenerationDto {
  id: string;
  status: ModelStatus;
  /** True when the worker started this itself after a capture finished. */
  isAutoGenerated: boolean;
  /**
   * Coarse progress 0–100 from the worker's live `progress` sub-doc, when it
   * has reported any. The owner sees only the NUMBER, never the phase name —
   * "PREPARING"/"FINALIZING" describe our pipeline internals and mean nothing
   * to someone who just wants to know how long they are waiting.
   */
  progressPercent?: number;
  /** Owner-safe failure copy — mapped codes only, never raw upstream text. */
  error?: { code: string; message: string };
  createdAt: string;
}

// ── Optimization eligibility ─────────────────────────────────────────────────

/**
 * Which models in a project ALREADY have an optimized derivative, as a set of
 * source model ids.
 *
 * "Already" means an OPT child that is QUEUED, PROCESSING or SUCCEEDED —
 * PRESENT AND NOT BROKEN. A FAILED child is deliberately NOT counted, so one
 * transient S3 blip cannot permanently remove the only way to optimize a model.
 * (Judgment call, flagged in the PR: it is a deliberate reading of "if opt is
 * present, remove the button".)
 *
 * One query for the whole list — the alternative is N+1 across a history that
 * a busy project fills with a dozen attempts.
 */
export async function optimizedSourceIdsFor(projectId: string): Promise<Set<string>> {
  const rows = await ProjectModel.find(
    {
      projectId: new Types.ObjectId(projectId),
      optimizedFrom: { $exists: true },
      status: { $in: ['QUEUED', 'PROCESSING', 'SUCCEEDED'] },
    },
    { optimizedFrom: 1 }
  ).exec();
  return new Set(rows.map((r) => r.optimizedFrom!.toHexString()));
}

/**
 * Is this model worth (and legal to) optimize?
 *
 * True iff ALL of:
 *   • it SUCCEEDED — there is nothing to shrink otherwise;
 *   • it has a GLB;
 *   • its size is KNOWN — an unknown size is not a small one, and rendering the
 *     button on a guess means offering an action the server will refuse;
 *   • that size is above MODEL_OPTIMIZE_THRESHOLD_BYTES;
 *   • it is not ITSELF an optimized record — optimizing an optimization is
 *     recursion with no product;
 *   • it has no live OPT child (see {@link optimizedSourceIdsFor}).
 *
 * [optimizedSourceIds] omitted means "the caller did not look" — and this then
 * FAILS CLOSED to false. Every surface that must show the button passes it; the
 * ones that don't are returning a record that was just created (QUEUED, so
 * false regardless), and a fail-closed default can only ever hide a button, not
 * offer one the server would reject.
 */
export function canOptimizeModel(
  record: IProjectModel,
  optimizedSourceIds?: ReadonlySet<string>
): boolean {
  if (!optimizedSourceIds) return false;
  if (record.status !== 'SUCCEEDED') return false;
  if (record.source === 'optimized') return false;
  if (!record.artifacts?.glbKey) return false;
  const bytes = record.artifacts.glbBytes;
  if (bytes === undefined) return false;
  if (bytes <= env.MODEL_OPTIMIZE_THRESHOLD_BYTES) return false;
  return !optimizedSourceIds.has(record.id as string);
}

export function toProjectModelDto(
  record: IProjectModel,
  optimizedSourceIds?: ReadonlySet<string>
): ProjectModelDto {
  return {
    id: record.id as string,
    projectId: record.projectId.toHexString(),
    jobId: record.jobId.toHexString(),
    source: record.source,
    status: record.status,
    selectedKeys: record.selectedKeys,
    // Only meaningful while pending: a terminal record's progress is cleared by
    // the worker, and clients ignore it for terminal statuses regardless.
    ...(record.progress
      ? { progress: { phase: record.progress.phase, percent: record.progress.percent } }
      : {}),
    // Only our CloudFront URLs ever leave this service — never an S3 key and
    // never a (long-expired) Meshy URL.
    ...(record.artifacts
      ? {
          artifacts: {
            glb: record.artifacts.cdnUrls.glb,
            ...(record.artifacts.cdnUrls.usdz ? { usdz: record.artifacts.cdnUrls.usdz } : {}),
            ...(record.artifacts.cdnUrls.preview
              ? { preview: record.artifacts.cdnUrls.preview }
              : {}),
          },
        }
      : {}),
    ...(record.approved ? { approved: { at: record.approved.at.toISOString() } } : {}),
    ...(record.error ? { error: { code: record.error.code, message: record.error.message } } : {}),
    // Mongoose hands back a sub-document; flatten it so the wire payload is
    // plain JSON and no internal document machinery leaks into the response.
    ...(record.generationTrace
      ? {
          generationTrace: {
            steps: record.generationTrace.steps.map((s) => ({
              step: s.step,
              status: s.status,
              ...(s.detail ? { detail: s.detail } : {}),
              at: s.at,
              durationMs: s.durationMs,
            })),
            ...(record.generationTrace.selection
              ? { selection: record.generationTrace.selection }
              : {}),
            requestedBy: record.generationTrace.requestedBy,
          },
        }
      : {}),
    ...(record.artifacts?.glbBytes !== undefined ? { glbBytes: record.artifacts.glbBytes } : {}),
    ...(record.optimizedFrom ? { optimizedFromId: record.optimizedFrom.toHexString() } : {}),
    ...(record.optimization
      ? {
          optimization: {
            sourceBytes: record.optimization.sourceBytes,
            outputBytes: record.optimization.outputBytes,
          },
        }
      : {}),
    canOptimize: canOptimizeModel(record, optimizedSourceIds),
    createdAt: record.createdAt.toISOString(),
    updatedAt: record.updatedAt.toISOString(),
  };
}

/**
 * The owner projection. The optimization fields added here are deliberately
 * the SMALL ones: a size, two booleans. No `optimizedFrom` ObjectId (it names
 * another record the owner cannot address), no S3 keys, no staff actor ids —
 * the minimalism of this DTO is the feature.
 */
function toOwnerModelDto(
  record: IProjectModel,
  optimizedSourceIds?: ReadonlySet<string>
): OwnerModelDto | null {
  if (!record.artifacts) return null;
  return {
    id: record.id as string,
    source: record.source,
    glbUrl: record.artifacts.cdnUrls.glb,
    ...(record.artifacts.cdnUrls.usdz ? { usdzUrl: record.artifacts.cdnUrls.usdz } : {}),
    ...(record.artifacts.cdnUrls.preview ? { previewUrl: record.artifacts.cdnUrls.preview } : {}),
    approved: record.approved !== undefined,
    isAutoGenerated: record.createdBySystem === true,
    ...(record.artifacts.glbBytes !== undefined ? { sizeBytes: record.artifacts.glbBytes } : {}),
    isOptimized: record.source === 'optimized',
    canOptimize: canOptimizeModel(record, optimizedSourceIds),
    createdAt: record.createdAt.toISOString(),
  };
}

/**
 * The owner LIST projection. Built field-by-field rather than by spreading a
 * record: a spread is how a staff-only field silently reaches an owner the next
 * time the schema grows, and this DTO's whole value is what it leaves out.
 */
function toOwnerModelListItemDto(
  record: IProjectModel,
  optimizedSourceIds?: ReadonlySet<string>
): OwnerModelListItemDto {
  return {
    id: record.id as string,
    source: record.source,
    status: record.status,
    // Only our CloudFront URLs, and only when the record actually has them.
    ...(record.artifacts
      ? {
          glbUrl: record.artifacts.cdnUrls.glb,
          ...(record.artifacts.cdnUrls.usdz ? { usdzUrl: record.artifacts.cdnUrls.usdz } : {}),
          ...(record.artifacts.cdnUrls.preview
            ? { previewUrl: record.artifacts.cdnUrls.preview }
            : {}),
          ...(record.artifacts.glbBytes !== undefined
            ? { sizeBytes: record.artifacts.glbBytes }
            : {}),
        }
      : {}),
    approved: record.approved !== undefined,
    isAutoGenerated: record.createdBySystem === true,
    isOptimized: record.source === 'optimized',
    canOptimize: canOptimizeModel(record, optimizedSourceIds),
    // The NUMBER only — `progress.phase` stays staff-side on purpose.
    ...(record.progress ? { progressPercent: record.progress.percent } : {}),
    ...(record.error ? { error: { code: record.error.code, message: record.error.message } } : {}),
    createdAt: record.createdAt.toISOString(),
  };
}

/**
 * A project's model history as the OWNER may see it, newest first.
 *
 * Same ordering and same records as {@link listProjectModels} — including
 * pending and FAILED ones, so the row the owner just created by tapping
 * Optimize is visible while it runs and explains itself if it breaks. The
 * difference is entirely in the projection.
 *
 * Takes a projectId that the CALLER has already proven the owner owns; this
 * function does no authorization of its own, exactly like the staff list.
 */
export async function listOwnerProjectModels(
  projectId: string
): Promise<OwnerModelListItemDto[]> {
  const records = await listProjectModels(projectId);
  // One query for the whole list, same as the staff surface — without it every
  // row's canOptimize would fail closed and the action would never appear.
  const optimizedSourceIds = await optimizedSourceIdsFor(projectId);
  return records.map((r) => toOwnerModelListItemDto(r, optimizedSourceIds));
}

// ── Create ───────────────────────────────────────────────────────────────────

export interface CreateMeshyModelRequestInput {
  projectId: string;
  /** RELATIVE export-manifest keys, exactly as the Preview gallery holds them. */
  keys: string[];
  actor: ModelActor;
  /**
   * `Idempotency-Key` header, when the client sent one. The automatic path
   * supplies a DERIVED key (`auto:{jobId}`) instead of a client-supplied one,
   * which is what makes a re-run of a capture job replay rather than pay twice.
   */
  idempotencyKey?: string;
  /** True when the worker started this itself (no human asked). */
  createdBySystem?: boolean;
  /**
   * True when a person pressed "Generate 3D model" and the SERVER selected the
   * photos. Distinct from `createdBySystem` (a human DID ask) and from a plain
   * staff request (a human picked the photos by hand) — it is what lets the
   * shared 24h ceiling count automatic and button-triggered spends together
   * while leaving hand-curated staff selections to their own rate window.
   */
  createdByManualButton?: boolean;
  /**
   * The capture job these keys came from, PINNING the generation to it.
   *
   * Omit it and the newest exportable job is resolved instead — which is what
   * the staff surfaces want, because a human is curating the project's current
   * state at request time. The AUTOMATIC path must always supply it: it is
   * acting on one specific job, and a project that gains a newer finalized
   * capture mid-flight would otherwise have these keys presigned under the
   * wrong prefix (see findExportableJobById).
   */
  jobId?: Types.ObjectId | string;
}

export type CreateMeshyModelResult =
  | { outcome: 'PROJECT_NOT_FOUND' }
  | { outcome: 'NOT_EXPORTABLE' }
  /** Selection size outside [MIN_SELECTED_PHOTOS, MAX_SELECTED_PHOTOS] AFTER dedupe. */
  | { outcome: 'INVALID_COUNT'; count: number }
  /** A key escapes the job prefix — the whole request is refused. */
  | { outcome: 'INVALID_KEY'; key: string }
  /** A record already existed for this (actor, Idempotency-Key) — NOT re-enqueued. */
  | { outcome: 'REPLAYED'; model: IProjectModel }
  | { outcome: 'CREATED'; model: IProjectModel };

/**
 * Validates a staff photo selection and enqueues one Meshy generation.
 *
 * Order matters for the money contract: the ProjectModel record is inserted
 * FIRST (the unique (actor, Idempotency-Key) index is the race authority — a
 * double-tap loses here with E11000 and replays the winner instead of paying
 * twice), and only then is the worker job enqueued. A crash between the two
 * leaves a QUEUED record with no job — visible and re-requestable — which is
 * strictly better than a job whose record does not exist yet.
 *
 * The keys are resolved against an exportable job — the caller's own when it
 * passes [CreateMeshyModelRequestInput.jobId], otherwise the same newest-job
 * rule the export and soft-delete paths use — and validated with the SAME
 * containment rule, so a caller can only ever select photos it can already see.
 */
/**
 * The idempotency key that makes a capture's FIRST server-selected generation
 * unique — SHARED by both the automatic capture-processor path
 * (`maybeAutoGenerateModel`) and the non-forced owner "Generate 3D model" button
 * (`generateModelOnDemand`). Because both attribute the record to the same owner
 * and use this same key, whichever trigger fires first wins, and the other
 * collides on the unique `(createdByUserId, idempotencyKey)` index and REPLAYS
 * the existing record instead of paying for a SECOND Meshy task. That is what
 * stops one capture becoming two models (two charges, two different meshes).
 *
 * Derived from the capture jobId (not random, not the project) so a genuine
 * recapture — a new job id — correctly earns its own deliberate generation. A
 * forced staff regenerate appends a random suffix (see
 * `manualGenerationIdempotencyKey`) so it does NOT collide.
 */
export function captureGenerationIdempotencyKey(jobId: Types.ObjectId | string): string {
  return `capture:${jobId.toString()}`;
}

export async function createMeshyModelRequest(
  input: CreateMeshyModelRequestInput
): Promise<CreateMeshyModelResult> {
  const { projectId, actor, idempotencyKey } = input;

  const project = await Project.findOne({
    _id: new Types.ObjectId(projectId),
    deletedAt: null,
  }).exec();
  if (!project) return { outcome: 'PROJECT_NOT_FOUND' };

  // An explicit jobId pins the generation to the caller's OWN job; without one
  // the newest exportable job is resolved, unchanged, for the staff path.
  // Only the EXPLICIT-jobId branch was widened, to
  // findModelSourceJobById — which matches an exportable CAPTURE job OR an
  // UPLOADED photo-upload job. The no-jobId branch is untouched, so the staff
  // "newest exportable capture" rule is exactly what it always was and export /
  // preview / soft-delete keep ignoring PHOTO_UPLOAD jobs entirely.
  const job = input.jobId
    ? await findModelSourceJobById(projectId, input.jobId)
    : await findExportableJob(projectId);
  if (!job || !job.upload) return { outcome: 'NOT_EXPORTABLE' };

  // Dedupe before counting: selecting the same photo twice is a 2-photo
  // selection, and sending Meshy a duplicate image wastes a view slot.
  const keys = [...new Set(input.keys)];
  if (keys.length < MIN_SELECTED_PHOTOS || keys.length > MAX_SELECTED_PHOTOS) {
    return { outcome: 'INVALID_COUNT', count: keys.length };
  }
  for (const key of keys) {
    if (!isContainedRelativeKey(key)) return { outcome: 'INVALID_KEY', key };
  }

  let record: IProjectModel;
  try {
    record = await ProjectModel.create({
      projectId: project._id,
      jobId: job._id,
      source: 'meshy' satisfies ModelSource,
      status: 'QUEUED',
      selectedKeys: keys,
      createdByUserId: new Types.ObjectId(actor.userId),
      createdByRole: actor.role,
      ...(input.createdBySystem ? { createdBySystem: true } : {}),
      ...(input.createdByManualButton ? { createdByManualButton: true } : {}),
      ...(idempotencyKey ? { idempotencyKey } : {}),
    });
  } catch (err: unknown) {
    if (isDuplicateKeyError(err) && idempotencyKey) {
      const existing = await ProjectModel.findOne({
        createdByUserId: new Types.ObjectId(actor.userId),
        idempotencyKey,
      }).exec();
      // The index guarantees the winner exists; if it somehow does not, fall
      // through and rethrow rather than silently paying for a second run.
      if (existing) return { outcome: 'REPLAYED', model: existing };
    }
    throw err;
  }

  try {
    await Job.create({
      projectId: project._id,
      userId: job.userId,
      jobType: MESHY_MODEL_GENERATION_JOB_TYPE,
      // The enqueue itself: the worker claims `state: 'QUEUED'` documents.
      state: 'QUEUED',
      payload: { modelId: record.id as string },
    });
  } catch (err: unknown) {
    // No job means nothing will ever run — fail the record now so it does not
    // sit QUEUED forever and the staff user gets a real error to retry from.
    record.status = 'FAILED';
    record.error = { code: 'ENQUEUE_FAILED', message: 'Could not enqueue the generation job.' };
    await record.save();
    throw err;
  }

  return { outcome: 'CREATED', model: record };
}

/**
 * How many SERVER-SELECTED generations one actor has accrued in the rolling 24h
 * window — automatic and "Generate 3D model" button presses counted together.
 *
 * ONE pool on purpose: it is the same money, and a per-source cap would just be
 * two ways to spend twice as much. Hand-curated staff selections are excluded —
 * those already have their own rate window, and a human choosing the photos is
 * a different risk from the selector choosing them unattended.
 */
export async function countServerSelectedGenerationsInLast24h(userId: string): Promise<number> {
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
  return ProjectModel.countDocuments({
    createdByUserId: new Types.ObjectId(userId),
    createdAt: { $gte: since },
    $or: [{ createdBySystem: true }, { createdByManualButton: true }],
  }).exec();
}

/**
 * Writes the decision trace onto a record AFTER the enqueue, so the ENQUEUE
 * step is itself part of it.
 *
 * BEST-EFFORT: by this point the generation is queued and the credits are
 * committed. Losing a debug artifact must never turn a successful, paid request
 * into an error the caller retries — which would pay again.
 */
export async function persistGenerationTrace(
  modelId: string,
  trace: ModelGenerationTrace
): Promise<void> {
  try {
    await ProjectModel.updateOne(
      { _id: new Types.ObjectId(modelId) },
      { $set: { generationTrace: trace } }
    ).exec();
  } catch {
    // Swallowed deliberately — see the doc comment.
  }
}

/** Widens the selector's trace into the loose shape the Mixed sub-doc stores,
 * so a counter added later is persisted rather than silently stripped. */
export function toStoredSelection(trace: object): Record<string, unknown> {
  return { ...trace } as Record<string, unknown>;
}

function isDuplicateKeyError(err: unknown): boolean {
  return typeof err === 'object' && err !== null && (err as { code?: number }).code === 11000;
}

// ── Edited model-input uploads (the client's "Prepare Images" screen) ────────

/** One presigned upload slot for an edited model-input image. */
export interface ModelImageUploadSlot {
  /** Job-root-RELATIVE key — pass this to Create-Model exactly like a
   * capture-photo key. Always under the reserved `model-input/` namespace. */
  key: string;
  /** Presigned PUT URL (Content-Type locked to image/jpeg). A WRITE bearer
   * credential — may appear ONLY in the route response, never in logs. */
  url: string;
}

export type CreateModelImageUploadsResult =
  | { outcome: 'PROJECT_NOT_FOUND' }
  | { outcome: 'NOT_EXPORTABLE' }
  | {
      outcome: 'CREATED';
      projectId: string;
      jobId: string;
      uploads: ModelImageUploadSlot[];
      expiresAt: string;
    };

/**
 * Presigns PUT slots for staff-EDITED copies of selected photos (crop /
 * background removal / lighting), so a Meshy generation can run on cleaned-up
 * inputs while the original captures stay untouched.
 *
 * The keys land under the exportable job's own prefix — in the reserved
 * `model-input/` namespace — so the EXISTING Create-Model containment check,
 * the worker's presigned-GET resolution, and the admin hard-delete purge all
 * apply to them with no special casing. Each call mints a fresh session id;
 * nothing is recorded in the DB (an abandoned session leaves only a few small
 * orphaned objects, purged with the project).
 *
 * Stateless like the capture upload-urls route: re-requesting is cheap and
 * idempotent in effect (new keys, no side effects), so it needs no
 * Idempotency-Key — the credit guards live on Create-Model, not here.
 */
export async function createModelImageUploadUrls(
  projectId: string,
  count: number
): Promise<CreateModelImageUploadsResult> {
  const project = await Project.findOne({
    _id: new Types.ObjectId(projectId),
    deletedAt: null,
  }).exec();
  if (!project) return { outcome: 'PROJECT_NOT_FOUND' };

  const job = await findExportableJob(projectId);
  if (!job || !job.upload) return { outcome: 'NOT_EXPORTABLE' };

  const { rawBucket, rawPrefix } = job.upload;
  const ttlSeconds = env.MODEL_IMAGE_UPLOAD_URL_TTL_SECONDS;
  const sessionId = randomUUID();
  const uploads = await Promise.all(
    Array.from({ length: count }, async (_, index) => {
      const key = `${MODEL_INPUT_KEY_PREFIX}${sessionId}/photo_${index + 1}.jpg`;
      return {
        key,
        url: await presignObjectPutUrl(rawBucket, `${rawPrefix}${key}`, ttlSeconds, 'image/jpeg'),
      };
    })
  );

  return {
    outcome: 'CREATED',
    projectId: project.id as string,
    jobId: job.id as string,
    uploads,
    expiresAt: new Date(Date.now() + ttlSeconds * 1000).toISOString(),
  };
}

export type ReadProjectPhotoBytesResult =
  | { outcome: 'PROJECT_NOT_FOUND' }
  | { outcome: 'NOT_EXPORTABLE' }
  | { outcome: 'INVALID_KEY' }
  | { outcome: 'OBJECT_NOT_FOUND' }
  | { outcome: 'OK'; projectId: string; body: Buffer; contentType: string };

/**
 * Reads ONE job-root-relative object's bytes for the staff Prepare-Images
 * screen — a read-through proxy so browser clients can load a capture without
 * the raw bucket serving CORS, and so a session outliving its presigned URL
 * (~1h) can still fetch. Native clients keep using the presigned URL directly
 * and only fall back here, so this stays off the hot path.
 *
 * Reuses the SAME `isContainedRelativeKey` guard as Create-Model: the key is
 * caller-supplied, and without containment this route would become an
 * arbitrary-object reader scoped only by bucket.
 */
export async function readProjectPhotoBytes(
  projectId: string,
  relativeKey: string
): Promise<ReadProjectPhotoBytesResult> {
  const project = await Project.findOne({
    _id: new Types.ObjectId(projectId),
    deletedAt: null,
  }).exec();
  if (!project) return { outcome: 'PROJECT_NOT_FOUND' };

  const job = await findExportableJob(projectId);
  if (!job || !job.upload) return { outcome: 'NOT_EXPORTABLE' };

  if (!isContainedRelativeKey(relativeKey)) return { outcome: 'INVALID_KEY' };

  const { rawBucket, rawPrefix } = job.upload;
  const fetched = await getObjectBytes(rawBucket, `${rawPrefix}${relativeKey}`);
  if (fetched.outcome === 'absent') return { outcome: 'OBJECT_NOT_FOUND' };

  return {
    outcome: 'OK',
    projectId: project.id as string,
    body: fetched.body,
    contentType: fetched.contentType,
  };
}

// ── Read ─────────────────────────────────────────────────────────────────────

/** One generation record by id, or null. */
export async function findProjectModelById(modelId: string): Promise<IProjectModel | null> {
  if (!Types.ObjectId.isValid(modelId)) return null;
  return ProjectModel.findById(new Types.ObjectId(modelId)).exec();
}

/** A project's full generation history, newest first (the staff compare view). */
export async function listProjectModels(projectId: string): Promise<IProjectModel[]> {
  const records = await ProjectModel.find({ projectId: new Types.ObjectId(projectId) })
    .sort({ createdAt: -1 })
    .exec();
  await backfillGlbBytes(records);
  return records;
}

/**
 * Fills in `artifacts.glbBytes` for records written before the field existed.
 *
 * Lazy and on the read path on purpose: the size is only ever needed to decide
 * whether to offer the Optimize button, and this is the one place that
 * question gets asked about a whole history at once. Every record is HEADed at
 * most once, ever — the value is written back.
 *
 * BEST-EFFORT IN BOTH DIRECTIONS. A HEAD that fails (or an object that has
 * gone) leaves the size UNKNOWN, which downstream reads as "no button" — never
 * as an error, because a staff user losing the whole model list over one S3
 * hiccup is far worse than a button that shows up on the next refresh. The
 * write-back is equally optional; the next list re-derives it.
 */
async function backfillGlbBytes(records: IProjectModel[]): Promise<void> {
  const pending = records.filter(
    (r) => r.status === 'SUCCEEDED' && r.artifacts?.glbKey && r.artifacts.glbBytes === undefined
  );
  if (pending.length === 0) return;

  await Promise.all(
    pending.map(async (record) => {
      try {
        const head = await headObject(BUCKET_ARTIFACTS, record.artifacts!.glbKey);
        if (head.outcome !== 'ok' || head.contentLength <= 0) return;
        // Mutate the in-memory record too, so THIS response already carries the
        // size rather than making the client refresh to see the button.
        record.artifacts!.glbBytes = head.contentLength;
        await ProjectModel.updateOne(
          { _id: record._id },
          { $set: { 'artifacts.glbBytes': head.contentLength } }
        ).exec();
      } catch {
        // Size stays unknown. See the doc comment.
      }
    })
  );
}

/**
 * The newest SUCCEEDED model for a project, or null.
 *
 * Filtered in the QUERY, not picked off the history list: a fresh regenerate
 * sits at the head of the history as QUEUED/PROCESSING, and "latest overall,
 * if it happens to be SUCCEEDED" would hide the good model the project already
 * has for the whole duration of the new run.
 *
 * BEHAVIOUR CHANGE (optimization): an OPT record is a SUCCEEDED record, so once
 * a model is optimized THIS returns the optimized one. That is the intent — the
 * owner should get the small file — and it is exactly why the optimization
 * processor COPIES the source's USDZ and preview onto the OPT record: without
 * them, the first optimization would silently kill AR Quick Look and the
 * project thumbnail.
 */
export async function latestSucceededModel(projectId: string): Promise<IProjectModel | null> {
  return ProjectModel.findOne({
    projectId: new Types.ObjectId(projectId),
    status: 'SUCCEEDED',
  })
    .sort({ createdAt: -1 })
    .exec();
}

/**
 * The newest SUCCEEDED model as the OWNER may see it — the only generation
 * surface the owner-facing project detail exposes.
 */
export async function latestOwnerModelFor(projectId: string): Promise<OwnerModelDto | null> {
  const record = await latestSucceededModel(projectId);
  if (!record) return null;
  // The owner's Optimize affordance needs the same child check the staff list
  // does — one extra small query, and the alternative is a button that 409s.
  const optimizedSourceIds = await optimizedSourceIdsFor(projectId);
  return toOwnerModelDto(record, optimizedSourceIds);
}

/**
 * The generation the owner is currently waiting on, or null.
 *
 * Returns the newest record that is NOT yet SUCCEEDED — QUEUED/PROCESSING while
 * it runs, and FAILED so the app can offer "try again" rather than silently
 * showing nothing after a failed automatic attempt.
 *
 * Paired with {@link latestOwnerModelFor}, never a replacement for it: while a
 * regenerate is in flight the owner keeps seeing the model they already have.
 *
 * OPTIMIZATION RECORDS ARE EXCLUDED. They are not generations: a running
 * optimization would otherwise put "creating your 3D model…" on the screen of
 * someone who already HAS their model and merely asked for a smaller copy of
 * it — and a failed one would offer "try again" for a generation that never
 * happened. The `source` filter, not the status one, is what keeps this
 * endpoint's meaning intact.
 */
export async function pendingOwnerGenerationFor(
  projectId: string
): Promise<OwnerGenerationDto | null> {
  const record = await ProjectModel.findOne({
    projectId: new Types.ObjectId(projectId),
    status: { $ne: 'SUCCEEDED' },
    source: { $ne: 'optimized' satisfies ModelSource },
  })
    .sort({ createdAt: -1 })
    .exec();
  if (!record) return null;

  return {
    id: record.id as string,
    status: record.status,
    isAutoGenerated: record.createdBySystem === true,
    // The worker's live sub-status, reduced to the one number an owner cares
    // about. The phase name stays staff-only.
    ...(record.progress ? { progressPercent: record.progress.percent } : {}),
    ...(record.error
      ? { error: { code: record.error.code, message: record.error.message } }
      : {}),
    createdAt: record.createdAt.toISOString(),
  };
}

// ── Approve ──────────────────────────────────────────────────────────────────

export type ApproveModelResult =
  | { outcome: 'MODEL_NOT_FOUND' }
  /** Only a SUCCEEDED record can be approved — there is nothing else to sign off. */
  | { outcome: 'NOT_APPROVABLE'; status: ModelStatus }
  | { outcome: 'APPROVED'; model: IProjectModel };

/**
 * The "we're satisfied with the Meshy result — no manual creation needed" gate.
 *
 * One conditional findOneAndUpdate fenced on status SUCCEEDED (the codebase's
 * no-transactions atomicity pattern), so it can never approve a record that
 * failed. Re-approving is idempotent: it re-stamps `approved` with the latest
 * actor rather than erroring, matching the rest of the admin surface's
 * double-tap tolerance.
 */
export async function approveModel(
  projectId: string,
  modelId: string,
  actor: ModelActor
): Promise<ApproveModelResult> {
  const updated = await ProjectModel.findOneAndUpdate(
    {
      _id: new Types.ObjectId(modelId),
      projectId: new Types.ObjectId(projectId),
      status: 'SUCCEEDED',
    },
    { $set: { approved: { at: new Date(), byUserId: new Types.ObjectId(actor.userId) } } },
    { new: true }
  ).exec();
  if (updated) return { outcome: 'APPROVED', model: updated };

  // The fenced write lost — distinguish "no such record" from "wrong status"
  // so the route can answer 404 vs 409. (Both are staff-only surfaces, so the
  // enumeration-safety rule that collapses these on owner routes doesn't apply.)
  const existing = await ProjectModel.findOne({
    _id: new Types.ObjectId(modelId),
    projectId: new Types.ObjectId(projectId),
  }).exec();
  if (!existing) return { outcome: 'MODEL_NOT_FOUND' };
  return { outcome: 'NOT_APPROVABLE', status: existing.status };
}

// ── Optimize ─────────────────────────────────────────────────────────────────

/** Why a model cannot be optimized — one stable code per rule in
 * {@link canOptimizeModel}, so the client can map each to its own copy. */
export type NotOptimizableReason =
  | 'NOT_SUCCEEDED'
  | 'NO_GLB'
  | 'SIZE_UNKNOWN'
  | 'BELOW_THRESHOLD'
  /**
   * A live OPT child already exists. Part of the vocabulary because it is one
   * of the six rules {@link canOptimizeModel} enforces, but
   * {@link requestModelOptimization} never returns it: a second request for a
   * model that already has one is a REPLAY (200 + the existing record), which
   * is more useful to the caller than a 409 telling them what they asked for
   * already happened.
   */
  | 'ALREADY_OPTIMIZED'
  | 'IS_OPTIMIZED';

export type RequestModelOptimizationResult =
  | { outcome: 'PROJECT_NOT_FOUND' }
  | { outcome: 'MODEL_NOT_FOUND' }
  | { outcome: 'NOT_OPTIMIZABLE'; reason: NotOptimizableReason }
  /**
   * An OPT record already existed — NOT re-enqueued. `sourceBytes` is the
   * SOURCE model's GLB size (known, since eligibility required it), carried on
   * both success outcomes so the route's analytics reports a real number
   * instead of approximating one from a record the worker has not filled in yet.
   */
  | { outcome: 'REPLAYED'; model: IProjectModel; sourceBytes: number }
  | { outcome: 'CREATED'; model: IProjectModel; sourceBytes: number };

/**
 * Creates the OPT record for [modelId] and enqueues the job that fills it in.
 *
 * THE SERVER IS THE AUTHORITY. The client's button visibility is a courtesy:
 * every condition {@link canOptimizeModel} checks is re-checked here against
 * fresh documents, and the unique partial index on `optimizedFrom` is what
 * actually makes "a model is optimized at most once" true — a concurrent double
 * tap has both requests pass the read checks, and the loser's E11000 resolves
 * to a REPLAY of the winner rather than a second record.
 *
 * Order mirrors the money contract in {@link createMeshyModelRequest}: insert
 * the record FIRST, enqueue the Job second. A crash in between leaves a QUEUED
 * record with no job — visible, and re-requestable — which is strictly better
 * than a job whose record does not exist. If the enqueue THROWS, the record is
 * flipped to FAILED so it cannot sit QUEUED forever.
 */
export async function requestModelOptimization(input: {
  projectId: string;
  modelId: string;
  actor: ModelActor;
}): Promise<RequestModelOptimizationResult> {
  const { projectId, modelId, actor } = input;

  const project = await Project.findOne({
    _id: new Types.ObjectId(projectId),
    deletedAt: null,
  }).exec();
  if (!project) return { outcome: 'PROJECT_NOT_FOUND' };

  if (!Types.ObjectId.isValid(modelId)) return { outcome: 'MODEL_NOT_FOUND' };
  const source = await ProjectModel.findOne({
    _id: new Types.ObjectId(modelId),
    projectId: project._id,
  }).exec();
  if (!source) return { outcome: 'MODEL_NOT_FOUND' };

  // Re-derived here rather than trusting canOptimizeModel's boolean, because
  // the ROUTE needs to say WHICH rule refused — a bare "409" on a button the
  // client just rendered is unexplainable to the person who tapped it.
  const reason = notOptimizableReasonFor(source);
  if (reason) return { outcome: 'NOT_OPTIMIZABLE', reason };
  // Guaranteed present: SIZE_UNKNOWN is one of the rules above.
  const sourceBytes = source.artifacts!.glbBytes!;

  const existing = await ProjectModel.findOne({ optimizedFrom: source._id }).exec();
  if (existing) {
    // A FAILED child does not block a retry — it is replaced, not replayed, so
    // one transient failure cannot permanently consume the single slot the
    // unique index allows.
    if (existing.status !== 'FAILED') {
      return { outcome: 'REPLAYED', model: existing, sourceBytes };
    }
    await ProjectModel.deleteOne({ _id: existing._id }).exec();
  }

  let record: IProjectModel;
  try {
    record = await ProjectModel.create({
      projectId: project._id,
      // The CAPTURE job, inherited from the source: the artifact key space is
      // anchored to its rawPrefix, so the OPT output lands beside the
      // generation it came from.
      jobId: source.jobId,
      source: 'optimized' satisfies ModelSource,
      status: 'QUEUED',
      // Nothing was selected — this is a derivative of one model, not of any
      // photos. An empty array is the honest answer, and every reader already
      // handles it (the history row simply prints no photo count).
      selectedKeys: [],
      optimizedFrom: source._id,
      createdByUserId: new Types.ObjectId(actor.userId),
      createdByRole: actor.role,
      // Neither createdBySystem nor createdByManualButton: optimization is not
      // a server-selected GENERATION and must never consume the 24h spend
      // ceiling that countServerSelectedGenerationsInLast24h enforces.
    });
  } catch (err: unknown) {
    if (isDuplicateKeyError(err)) {
      const winner = await ProjectModel.findOne({ optimizedFrom: source._id }).exec();
      // The index guarantees a winner exists; if it somehow does not, rethrow
      // rather than silently doing nothing.
      if (winner) return { outcome: 'REPLAYED', model: winner, sourceBytes };
    }
    throw err;
  }

  try {
    await Job.create({
      projectId: project._id,
      userId: project.userId,
      jobType: MODEL_OPTIMIZATION_JOB_TYPE,
      state: 'QUEUED',
      payload: { modelId: record.id as string },
    });
  } catch (err: unknown) {
    record.status = 'FAILED';
    record.error = { code: 'ENQUEUE_FAILED', message: 'Could not enqueue the optimization job.' };
    await record.save();
    throw err;
  }

  return { outcome: 'CREATED', model: record, sourceBytes };
}

/**
 * The first rule {@link canOptimizeModel} would fail on, or null if none do.
 *
 * Deliberately ordered most-fundamental first, so the reason a caller gets is
 * the most useful one: "this hasn't finished generating" beats "its size is
 * unknown" for a record that is still PROCESSING.
 *
 * Note this does NOT check for an existing OPT child — that is a separate
 * lookup in the caller, because it is also where the FAILED-child retry is
 * decided.
 */
function notOptimizableReasonFor(record: IProjectModel): NotOptimizableReason | null {
  if (record.source === 'optimized') return 'IS_OPTIMIZED';
  if (record.status !== 'SUCCEEDED') return 'NOT_SUCCEEDED';
  if (!record.artifacts?.glbKey) return 'NO_GLB';
  if (record.artifacts.glbBytes === undefined) return 'SIZE_UNKNOWN';
  if (record.artifacts.glbBytes <= env.MODEL_OPTIMIZE_THRESHOLD_BYTES) return 'BELOW_THRESHOLD';
  return null;
}

/** Re-exported for the routes' 409 copy — see {@link NotOptimizableReason}. */
export const NOT_OPTIMIZABLE_CODES: Record<NotOptimizableReason, string> = {
  NOT_SUCCEEDED: 'MODEL_NOT_READY',
  NO_GLB: 'MODEL_NOT_READY',
  SIZE_UNKNOWN: 'MODEL_SIZE_UNKNOWN',
  BELOW_THRESHOLD: 'MODEL_ALREADY_SMALL',
  ALREADY_OPTIMIZED: 'ALREADY_OPTIMIZED',
  IS_OPTIMIZED: 'ALREADY_OPTIMIZED',
};

/** User-safe copy per reason. Says what is true, never what our pipeline is. */
export const NOT_OPTIMIZABLE_MESSAGES: Record<NotOptimizableReason, string> = {
  NOT_SUCCEEDED: 'This model has not finished generating yet.',
  NO_GLB: 'This model has no 3D file to optimize.',
  SIZE_UNKNOWN: "We couldn't determine this model's size. Try again in a moment.",
  BELOW_THRESHOLD: 'This model is already small enough.',
  ALREADY_OPTIMIZED: 'This model has already been optimized.',
  IS_OPTIMIZED: 'This model is already an optimized version.',
};
