// tests/owner-model-list.test.ts
//
// `GET /projects/:id/models` — the OWNER-facing model history.
//
// The load-bearing assertions, in order of what they protect:
//   1. the response leaks NO staff-only field. Asserted as a whole-key-set
//      comparison, not a handful of `toBeUndefined()`s: a spot check passes
//      forever while a new staff field quietly rides along on the next schema
//      change, which is precisely how this class of bug ships.
//   2. it is scoped to the caller's own project — another user's project is an
//      identical 404, never a list, and never a 403 that would confirm the
//      project exists.
//   3. pending and FAILED rows ARE included. The row an owner most needs right
//      after tapping Optimize is the QUEUED one; dropping it would make the
//      action look like it did nothing.
//   4. `canOptimize` is computed against the OPT-child set, so the owner list
//      agrees with the owner optimize endpoint rather than offering a button
//      the server would 409.
//
// Hermetic: in-memory MongoDB, no worker, no S3.
import { describe, it, expect, beforeAll, afterAll, afterEach } from 'vitest';
import request from 'supertest';
import mongoose, { Types } from 'mongoose';
import jwt from 'jsonwebtoken';
import { MongoMemoryServer } from 'mongodb-memory-server';

import { createApp } from '@/app';
import { env } from '@/config/env';
import { User, type UserRole } from '@/models/User';
import { Project } from '@/models/Project';
import { Job } from '@/models/Job';
import { ProjectModel, type IProjectModel } from '@/models/ProjectModel';
import { buildJobKeyPrefix } from '@/utils/s3Keys';
import { listOwnerProjectModels } from '@/services/projectModelsService';

const app = createApp();
let mongod: MongoMemoryServer;

/** Comfortably over MODEL_OPTIMIZE_THRESHOLD_BYTES (8 MiB). */
const BIG = 21 * 1024 * 1024;
/** Comfortably under it. */
const SMALL = 2 * 1024 * 1024;

/**
 * Every key the OWNER list is allowed to return. The test asserts the response
 * uses only these — so adding a field to the DTO is a deliberate act that
 * updates this list, not something that happens by accident.
 */
const ALLOWED_KEYS = new Set([
  'id',
  'source',
  'status',
  'glbUrl',
  'usdzUrl',
  'previewUrl',
  'approved',
  'isAutoGenerated',
  'sizeBytes',
  'isOptimized',
  'canOptimize',
  'progressPercent',
  'error',
  'createdAt',
]);

/**
 * Keys that exist on the STAFF DTO and must never appear here. Listed
 * explicitly as well as covered by ALLOWED_KEYS, because naming them is what
 * makes a failure say WHICH leak happened.
 */
const FORBIDDEN_KEYS = [
  'selectedKeys',
  'generationTrace',
  'projectId',
  'jobId',
  'optimizedFromId',
  'optimization',
  'updatedAt',
  'progress',
];

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  await mongoose.connect(mongod.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongod.stop();
});

afterEach(async () => {
  await User.deleteMany({});
  await Project.deleteMany({});
  await Job.deleteMany({});
  await ProjectModel.deleteMany({});
});

async function makeUser(
  role: UserRole | undefined
): Promise<{ id: string; auth: { Authorization: string } }> {
  const user = await User.create({
    authProvider: 'custom',
    authUid: `test|${new Types.ObjectId().toHexString()}`,
    ...(role ? { role } : {}),
  });
  const id = user.id as string;
  const token = jwt.sign({ userId: id, authUid: user.authUid }, env.JWT_SECRET, {
    expiresIn: '15m',
  });
  return { id, auth: { Authorization: `Bearer ${token}` } };
}

/** A project + its capture job, with no models yet. */
async function seedProject(ownerId: string) {
  const project = await Project.create({
    userId: new Types.ObjectId(ownerId),
    name: `P-${new Types.ObjectId().toHexString().slice(-6)}`,
    objectSize: 'MEDIUM',
    mode: 'GUIDED',
    status: 'PROCESSING',
  });
  const jobId = new Types.ObjectId();
  const prefix = buildJobKeyPrefix({
    userId: ownerId,
    projectId: project.id as string,
    jobId: jobId.toHexString(),
  });
  await Job.create({
    _id: jobId,
    projectId: project._id,
    userId: new Types.ObjectId(ownerId),
    state: 'QUEUED',
    upload: {
      uploadMethod: 'S3_PRESIGNED_MULTIPART',
      expectedFilesCount: 3,
      uploadedFilesCount: 3,
      checksumAlgo: 'md5',
      rawBucket: 'recapture-test-raw',
      rawPrefix: prefix,
      manifestKey: `${prefix}capture_manifest.json`,
    },
  });
  return { project, jobId, prefix };
}

/** One model on an existing project. `createdAt` is settable for ordering. */
async function addModel(
  project: { _id: Types.ObjectId; id: unknown },
  jobId: Types.ObjectId,
  prefix: string,
  ownerId: string,
  overrides: Partial<IProjectModel> & { withArtifacts?: boolean; bytes?: number } = {}
): Promise<IProjectModel> {
  const { withArtifacts = true, bytes = BIG, ...rest } = overrides;
  const glbKey = `${prefix}models/${new Types.ObjectId().toHexString()}/model.glb`;
  const doc = await ProjectModel.create({
    projectId: project._id,
    jobId,
    source: 'meshy',
    status: 'SUCCEEDED',
    // Staff-only field, deliberately POPULATED so the leak test is meaningful:
    // asserting its absence on a record that never had it proves nothing.
    selectedKeys: ['images/EYE/a.jpg', 'images/EYE/b.jpg', 'images/TOP/c.jpg'],
    createdByUserId: new Types.ObjectId(ownerId),
    createdByRole: 'MODEL_ARTIST',
    ...(withArtifacts
      ? {
          artifacts: {
            glbKey,
            cdnUrls: {
              glb: `https://cdn.example/${glbKey}`,
              usdz: `https://cdn.example/${glbKey}.usdz`,
              preview: `https://cdn.example/${glbKey}.png`,
            },
            glbBytes: bytes,
          },
        }
      : {}),
    ...rest,
  });
  return doc;
}

describe('GET /projects/:id/models — owner scoping', () => {
  it('returns the caller’s own project models', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    expect(res.status).toBe(200);
    expect(res.body.status).toBe('success');
    expect(res.body.models).toHaveLength(1);
  });

  it('another user’s project is an identical 404 — never a list, never a 403', async () => {
    const owner = await makeUser('USER');
    const stranger = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(stranger.auth);

    expect(res.status).toBe(404);
    expect(res.body.code).toBe('NOT_FOUND');
    expect(res.body.models).toBeUndefined();
  });

  it('a project that does not exist is the SAME 404 — unenumerable', async () => {
    const owner = await makeUser('USER');
    const res = await request(app)
      .get(`/projects/${new Types.ObjectId().toHexString()}/models`)
      .set(owner.auth);

    expect(res.status).toBe(404);
    expect(res.body.code).toBe('NOT_FOUND');
  });

  it('STAFF are not special-cased — the route is scoped by OWNERSHIP', async () => {
    // An ADMIN who does not own the project gets the same 404 as anyone else.
    // Staff read models through /admin, which is where their privilege lives;
    // this route must not become a second, weaker door to the same data.
    const owner = await makeUser('USER');
    const admin = await makeUser('ADMIN');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(admin.auth);

    expect(res.status).toBe(404);
  });

  it('rejects a malformed project id with 400, without touching the DB', async () => {
    const owner = await makeUser('USER');
    const res = await request(app).get('/projects/not-an-id/models').set(owner.auth);
    expect(res.status).toBe(400);
    expect(res.body.code).toBe('INVALID_REQUEST');
  });

  it('requires authentication', async () => {
    const owner = await makeUser('USER');
    const { project } = await seedProject(owner.id);
    const res = await request(app).get(`/projects/${project.id}/models`);
    expect(res.status).toBe(401);
  });
});

describe('GET /projects/:id/models — the owner-safe projection', () => {
  it('leaks NO staff-only field — whole key set, not a spot check', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      approved: { at: new Date(), byUserId: new Types.ObjectId(owner.id) },
      generationTrace: {
        steps: [{ step: 'SELECT_PHOTOS', status: 'OK', at: new Date(), durationMs: 12 }],
        requestedBy: 'AUTO',
      },
    } as Partial<IProjectModel>);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    expect(res.status).toBe(200);
    const row = res.body.models[0];

    // 1. Nothing outside the allow-list.
    const unexpected = Object.keys(row).filter((k) => !ALLOWED_KEYS.has(k));
    expect(unexpected).toEqual([]);

    // 2. And the staff fields by name, so a failure says which one leaked.
    for (const key of FORBIDDEN_KEYS) {
      expect(row[key]).toBeUndefined();
    }

    // 3. The record really did carry the staff data — otherwise (1) and (2)
    //    would be passing against a record that had nothing to leak.
    const stored = await ProjectModel.findById(row.id).exec();
    expect(stored!.selectedKeys).toHaveLength(3);
    expect(stored!.generationTrace).toBeDefined();

    // 4. No raw S3 KEY FIELD. Deliberately not a substring check on the
    //    payload: a CloudFront URL is built as `{base}/{key}`, so the key path
    //    legitimately appears inside the URL. What must never appear is a
    //    bare key field naming our bucket layout as a thing to address.
    expect(row.glbKey).toBeUndefined();
    expect(row.usdzKey).toBeUndefined();
    expect(row.previewImageKey).toBeUndefined();
    expect(row.artifacts).toBeUndefined();
  });

  it('carries the fields the owner list screen renders', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      createdBySystem: true,
    } as Partial<IProjectModel>);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    const row = res.body.models[0];
    expect(row.status).toBe('SUCCEEDED');
    expect(row.source).toBe('meshy');
    expect(row.glbUrl).toMatch(/^https:\/\/cdn\.example\//);
    expect(row.usdzUrl).toBeDefined();
    expect(row.previewUrl).toBeDefined();
    expect(row.sizeBytes).toBe(BIG);
    expect(row.isOptimized).toBe(false);
    expect(row.isAutoGenerated).toBe(true);
    expect(row.approved).toBe(false);
    expect(typeof row.createdAt).toBe('string');
  });

  it('newest first', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    const older = await addModel(project, jobId, prefix, owner.id, {
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
    } as Partial<IProjectModel>);
    const newer = await addModel(project, jobId, prefix, owner.id, {
      createdAt: new Date('2026-02-01T00:00:00.000Z'),
    } as Partial<IProjectModel>);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    expect(res.body.models.map((m: { id: string }) => m.id)).toEqual([
      newer.id,
      older.id,
    ]);
  });

  it('INCLUDES pending and FAILED rows — the list is a history, not a shelf', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      status: 'QUEUED',
      withArtifacts: false,
    } as never);
    await addModel(project, jobId, prefix, owner.id, {
      status: 'FAILED',
      withArtifacts: false,
      error: { code: 'MESHY_FAILED', message: 'We couldn’t build this model.' },
    } as never);
    await addModel(project, jobId, prefix, owner.id);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    const statuses = res.body.models.map((m: { status: string }) => m.status).sort();
    expect(statuses).toEqual(['FAILED', 'QUEUED', 'SUCCEEDED']);

    // A record with no artifacts has no URL — and that is representable,
    // rather than being a reason to drop the row.
    const queued = res.body.models.find((m: { status: string }) => m.status === 'QUEUED');
    expect(queued.glbUrl).toBeUndefined();
    expect(queued.canOptimize).toBe(false);
  });

  it('ships the owner-safe error copy on a FAILED row, and no more', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      status: 'FAILED',
      withArtifacts: false,
      error: { code: 'MESHY_FAILED', message: 'We couldn’t build this model.' },
    } as never);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    const row = res.body.models[0];
    expect(row.error).toEqual({
      code: 'MESHY_FAILED',
      message: 'We couldn’t build this model.',
    });
  });

  it('reports progress as a bare PERCENT — never the phase name', async () => {
    // The phase vocabulary (PREPARING/FINALIZING) describes our pipeline
    // internals; the owner gets the number only.
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      status: 'PROCESSING',
      withArtifacts: false,
      progress: { phase: 'GENERATING', percent: 42 },
    } as never);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    const row = res.body.models[0];
    expect(row.progressPercent).toBe(42);
    expect(row.progress).toBeUndefined();
    expect(JSON.stringify(row)).not.toContain('GENERATING');
  });
});

describe('GET /projects/:id/models — canOptimize agrees with the optimize route', () => {
  it('true for a big SUCCEEDED model with a known size', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    await addModel(project, jobId, prefix, owner.id);

    const res = await request(app)
      .get(`/projects/${project.id}/models`)
      .set(owner.auth);

    expect(res.body.models[0].canOptimize).toBe(true);
  });

  it('false below the threshold, and false when the size is UNKNOWN', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    const small = await addModel(project, jobId, prefix, owner.id, { bytes: SMALL } as never);
    // Unknown size: artifacts present, glbBytes absent. NOT the same as small.
    const unknown = await addModel(project, jobId, prefix, owner.id);
    await ProjectModel.updateOne(
      { _id: unknown._id },
      { $unset: { 'artifacts.glbBytes': 1 } }
    ).exec();

    const rows = await listOwnerProjectModels(project.id as string);
    const byId = new Map(rows.map((r) => [r.id, r]));
    expect(byId.get(small.id as string)!.canOptimize).toBe(false);
    // NOTE: the read path backfills glbBytes from S3 when it can. There is no
    // S3 here, so the HEAD fails and the size stays unknown — which is exactly
    // the state under test.
    expect(byId.get(unknown.id as string)!.canOptimize).toBe(false);
    expect(byId.get(unknown.id as string)!.sizeBytes).toBeUndefined();
  });

  it('false once a live OPT child exists, true again if that child FAILED', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    const source = await addModel(project, jobId, prefix, owner.id);

    const child = await ProjectModel.create({
      projectId: project._id,
      jobId,
      source: 'optimized',
      status: 'QUEUED',
      selectedKeys: [],
      optimizedFrom: source._id,
      createdByUserId: new Types.ObjectId(owner.id),
      createdByRole: 'USER',
    });

    let rows = await listOwnerProjectModels(project.id as string);
    expect(rows.find((r) => r.id === (source.id as string))!.canOptimize).toBe(false);

    // A transient failure must not permanently remove the only way to optimize.
    await ProjectModel.updateOne({ _id: child._id }, { $set: { status: 'FAILED' } }).exec();
    rows = await listOwnerProjectModels(project.id as string);
    expect(rows.find((r) => r.id === (source.id as string))!.canOptimize).toBe(true);
  });

  it('false on the OPT record itself — optimizing an optimization is recursion', async () => {
    const owner = await makeUser('USER');
    const { project, jobId, prefix } = await seedProject(owner.id);
    const source = await addModel(project, jobId, prefix, owner.id);
    await addModel(project, jobId, prefix, owner.id, {
      source: 'optimized',
      optimizedFrom: source._id,
    } as never);

    const rows = await listOwnerProjectModels(project.id as string);
    const opt = rows.find((r) => r.isOptimized)!;
    expect(opt.canOptimize).toBe(false);
    expect(opt.isOptimized).toBe(true);
  });
});
