// lib/domain/entities/project_model.dart
//
// Typed model of one 3D-model GENERATION record, as both the staff surface
// (`/admin/projects/:id/models`) and the owner surface (`GET /projects/:id`'s
// `model`) return it. Hand-synced with the backend's ProjectModelDto /
// OwnerModelDto (recapture-api/src/services/projectModelsService.ts) — there is
// no shared package, so a change on either side must be mirrored here.
//
// The staff and owner payloads differ deliberately: the owner one carries no
// keys, no selection and no staff actor ids. This entity models the UNION and
// leaves the staff-only fields null when parsed from the owner shape.
import 'generation_trace.dart';

/// Where the model came from. Drives the "Created by Meshy AI" badge — the badge
/// is never inferred from anything else.
enum ModelSource {
  meshy,
  manual,

  /// Not an ORIGIN but a DERIVATIVE: this record is another model's GLB run
  /// through the backend's glTF-Transform pipeline. It costs no generation
  /// credits and always has a source model behind it.
  optimized,

  /// A source this build does not know (server ahead of the app). Renders
  /// unbadged rather than crashing the viewer.
  unknown;

  static ModelSource parse(Object? raw) => switch (raw.toString()) {
        'meshy' => ModelSource.meshy,
        'manual' => ModelSource.manual,
        'optimized' => ModelSource.optimized,
        _ => ModelSource.unknown,
      };

  /// The origin label shown on the viewer, or null when there is nothing to
  /// attribute.
  ///
  /// `optimized` returns NULL deliberately: the OPT chip is its own thing, and
  /// a row that also said "Created by Maya AI" would be claiming an origin for
  /// a record that has none — the model it was derived from holds that fact.
  String? get badgeLabel => switch (this) {
        ModelSource.meshy => 'Created by Maya AI',
        ModelSource.manual ||
        ModelSource.optimized ||
        ModelSource.unknown =>
          null,
      };
}

/// The badge shown on an AUTOMATICALLY generated model.
///
/// Deliberately says "preview quality": a model built from four auto-selected
/// photos is good, not finished. Presented as a product it disappoints;
/// presented as an AI preview it delights, and it makes the Regenerate
/// affordance next to it read as an invitation rather than an apology.
const String kAutoGeneratedBadgeLabel = 'AI generated — preview quality';

/// Generation lifecycle. `QUEUED`/`PROCESSING` are the polling states.
enum ModelStatus {
  queued,
  processing,
  succeeded,
  failed,
  /// Unknown to this build — treated as terminal so polling can't spin forever.
  unknown;

  static ModelStatus parse(Object? raw) => switch (raw.toString()) {
        'QUEUED' => ModelStatus.queued,
        'PROCESSING' => ModelStatus.processing,
        'SUCCEEDED' => ModelStatus.succeeded,
        'FAILED' => ModelStatus.failed,
        _ => ModelStatus.unknown,
      };

  /// Whether a generation in this state is still expected to change — the
  /// polling loop's stop condition.
  bool get isPending => this == ModelStatus.queued || this == ModelStatus.processing;
}

/// What the backend worker is doing RIGHT NOW inside a PROCESSING record.
/// Mirrors ProjectModelDto's `progress.phase`. Display-only.
enum ModelProgressPhase {
  /// Presigning the selected photos / submitting the Meshy task.
  preparing,
  /// Meshy is building the model — [ModelProgress.percent] is Meshy's own 0–100.
  generating,
  /// Downloading Meshy's results and re-hosting them on our S3.
  finalizing,
  /// A phase this build does not know (server ahead of the app). Renders as a
  /// generic "working…" step rather than crashing or hiding progress.
  unknown;

  static ModelProgressPhase parse(Object? raw) => switch (raw.toString()) {
        'PREPARING' => ModelProgressPhase.preparing,
        'GENERATING' => ModelProgressPhase.generating,
        'FINALIZING' => ModelProgressPhase.finalizing,
        _ => ModelProgressPhase.unknown,
      };
}

/// Live sub-status of a pending generation — the staff progress UI's data.
/// Staff payload only, and OPTIONAL: an older backend (or a record written
/// before the field existed) simply has none, and the UI falls back to the
/// phase-less copy it showed before.
class ModelProgress {
  const ModelProgress({required this.phase, required this.percent});

  final ModelProgressPhase phase;

  /// 0–100 within [phase]; clamped so a malformed payload can't overflow a
  /// progress bar.
  final int percent;

  static ModelProgress? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final percent = raw['percent'];
    return ModelProgress(
      phase: ModelProgressPhase.parse(raw['phase']),
      percent: percent is num ? percent.round().clamp(0, 100) : 0,
    );
  }
}

/// Why a generation failed. Mirrors ProjectModelDto's `error`.
///
/// [message] is SAFE to display: the backend contract is that meshyClient never
/// interpolates a response body or a presigned URL into one. Staff payload only.
class ModelError {
  const ModelError({required this.code, required this.message});

  final String code;
  final String message;

  static ModelError? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final message = (raw['message'] ?? '').toString();
    if (message.isEmpty) return null;
    return ModelError(code: (raw['code'] ?? '').toString(), message: message);
  }
}

/// One generation attempt.
class ProjectModelView {
  const ProjectModelView({
    required this.id,
    required this.source,
    required this.status,
    this.glbUrl,
    this.usdzUrl,
    this.previewUrl,
    this.approved = false,
    this.selectedKeys = const [],
    this.createdAt,
    this.error,
    this.progress,
    this.isAutoGenerated = false,
    this.generationTrace,
    this.sizeBytes,
    this.isOptimized = false,
    this.canOptimize = false,
    this.optimizationSavingPercent,
  });

  final String id;
  final ModelSource source;
  final ModelStatus status;

  /// Whether the backend generated this itself after the capture finished,
  /// with no human choosing photos. Drives [kAutoGeneratedBadgeLabel] and the
  /// Regenerate affordance. Defaults false so a payload from an older backend
  /// (or the staff shape, which never sets it) reads as human-requested.
  final bool isAutoGenerated;

  /// Our CloudFront GLB URL — non-null exactly when [status] is succeeded.
  final String? glbUrl;

  /// Our CloudFront USDZ URL — iOS AR Quick Look's format. An AR enhancement
  /// only: Meshy doesn't always produce one, so it never gates [isViewable].
  final String? usdzUrl;
  final String? previewUrl;

  /// Whether staff signed off on this model ("no manual creation needed").
  final bool approved;

  /// The photos this attempt used. Staff payload only — empty for an owner.
  final List<String> selectedKeys;

  /// When the attempt was requested — how the history labels its rows (an index
  /// would renumber itself as new generations land at the head of the list).
  /// Null when the timestamp is absent or malformed.
  final DateTime? createdAt;

  /// The failure, for a FAILED record. Staff payload only — the owner endpoint
  /// never returns a failed attempt, so [tryFromOwnerMap] never parses this.
  final ModelError? error;

  /// Live worker sub-status while [status] is pending. Staff payload only, and
  /// null whenever the backend hasn't reported one (older server, QUEUED record,
  /// terminal record) — the UI must always have a phase-less fallback.
  final ModelProgress? progress;

  /// How this generation was decided — the server's request steps and the photo
  /// selector's counters. STAFF payload only, and null for every record written
  /// before the trace existed, so any reader must treat it as absent-by-default.
  final GenerationTrace? generationTrace;

  /// Size of the GLB in bytes, when the backend knows it.
  ///
  /// NULL MEANS UNKNOWN, NOT SMALL — a record predating the backend's size
  /// field has none until the list backfills it. The size line must render
  /// nothing rather than "0 B", and [canOptimize] is already false in that case
  /// because the server refuses to guess either.
  final int? sizeBytes;

  /// True when this record IS the optimized derivative of another model — the
  /// `OPT` chip's only input.
  final bool isOptimized;

  /// THE SERVER'S VERDICT on whether the Optimize action belongs on this row.
  ///
  /// Not recomputed here from [sizeBytes] and a local threshold: the moment the
  /// client owns a copy of that rule the two can disagree, and the disagreement
  /// only shows up as a button that 409s. Defaults false so an older backend
  /// (which sends no such field) simply shows no button.
  final bool canOptimize;

  /// How much smaller the optimization made it, 0–100, when this is an OPT
  /// record whose numbers the backend reported. Null on every other row.
  final int? optimizationSavingPercent;

  bool get isViewable => status == ModelStatus.succeeded && glbUrl != null;

  /// Parses the STAFF shape (`/admin/projects/:id/models` items), where the
  /// URLs live under `artifacts`.
  static ProjectModelView? tryFromStaffMap(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    if (id.isEmpty) return null;
    final artifacts = raw['artifacts'];
    return ProjectModelView(
      id: id,
      source: ModelSource.parse(raw['source']),
      status: ModelStatus.parse(raw['status']),
      glbUrl: artifacts is Map ? artifacts['glb'] as String? : null,
      usdzUrl: artifacts is Map ? artifacts['usdz'] as String? : null,
      previewUrl: artifacts is Map ? artifacts['preview'] as String? : null,
      approved: raw['approved'] != null,
      selectedKeys: [
        if (raw['selectedKeys'] case final List keys)
          for (final k in keys) k.toString(),
      ],
      // A malformed timestamp yields null rather than throwing — a history row
      // that can't be labelled is still worth showing.
      createdAt: DateTime.tryParse((raw['createdAt'] ?? '').toString()),
      error: ModelError.tryParse(raw['error']),
      progress: ModelProgress.tryParse(raw['progress']),
      generationTrace: GenerationTrace.tryParse(raw['generationTrace']),
      // Every one of these degrades to the SAFE value when absent, so an older
      // backend renders no badge and no button rather than throwing.
      sizeBytes: _asPositiveInt(raw['glbBytes']),
      isOptimized: ModelSource.parse(raw['source']) == ModelSource.optimized,
      canOptimize: raw['canOptimize'] == true,
      optimizationSavingPercent: _savingPercent(raw['optimization']),
    );
  }

  /// Parses the OWNER shape (`GET /projects/:id` → `model`), which is flat and
  /// only ever describes a finished model.
  static ProjectModelView? tryFromOwnerMap(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    final glb = (raw['glbUrl'] ?? '').toString();
    if (id.isEmpty || glb.isEmpty) return null;
    return ProjectModelView(
      id: id,
      source: ModelSource.parse(raw['source']),
      // The owner endpoint only ever returns a SUCCEEDED model.
      status: ModelStatus.succeeded,
      glbUrl: glb,
      usdzUrl: raw['usdzUrl'] as String?,
      previewUrl: raw['previewUrl'] as String?,
      approved: raw['approved'] == true,
      isAutoGenerated: raw['isAutoGenerated'] == true,
      createdAt: DateTime.tryParse((raw['createdAt'] ?? '').toString()),
      // The owner payload names the size `sizeBytes` (they are told how big
      // their download is, not which artifact it is) and ships `isOptimized`
      // as its own boolean rather than making the client read `source`.
      sizeBytes: _asPositiveInt(raw['sizeBytes']),
      isOptimized: raw['isOptimized'] == true,
      canOptimize: raw['canOptimize'] == true,
      // NO `optimization` on the owner DTO — the owner is not shown a
      // before/after saving for a file they never saw the "before" of.
      // NO `error` here, deliberately: the owner endpoint only ever returns a
      // SUCCEEDED model, so parsing one would only invite leaking a failure
      // (and the staff copy that goes with it) onto the owner's surface.
    );
  }

  /// Parses the OWNER LIST shape (`GET /projects/:id/models` items).
  ///
  /// Differs from [tryFromOwnerMap] in exactly the two ways the backend's
  /// OwnerModelListItemDto differs from OwnerModelDto:
  ///
  ///  * `status` is REAL here rather than assumed succeeded — a list has to
  ///    show the QUEUED row the user just created by tapping Optimize;
  ///  * `glbUrl` is therefore OPTIONAL, so a record with no artifacts yet is
  ///    kept (and rendered as pending) instead of being dropped. Dropping it
  ///    would make Optimize look like it did nothing.
  ///
  /// Still owner-safe by construction: there is no `selectedKeys`,
  /// `generationTrace` or `optimization` in this payload, so those stay at
  /// their empty/null defaults and the staff-only UI branches simply never
  /// light up. `progress` is rebuilt from the bare `progressPercent` the owner
  /// DTO carries, with an [ModelProgressPhase.unknown] phase — the backend
  /// deliberately withholds the phase NAME from owners.
  static ProjectModelView? tryFromOwnerListMap(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    if (id.isEmpty) return null;
    final glb = (raw['glbUrl'] ?? '').toString();
    final percent = raw['progressPercent'];
    return ProjectModelView(
      id: id,
      source: ModelSource.parse(raw['source']),
      status: ModelStatus.parse(raw['status']),
      glbUrl: glb.isEmpty ? null : glb,
      usdzUrl: raw['usdzUrl'] as String?,
      previewUrl: raw['previewUrl'] as String?,
      approved: raw['approved'] == true,
      isAutoGenerated: raw['isAutoGenerated'] == true,
      createdAt: DateTime.tryParse((raw['createdAt'] ?? '').toString()),
      error: ModelError.tryParse(raw['error']),
      progress: percent is num
          ? ModelProgress(
              phase: ModelProgressPhase.unknown,
              percent: percent.round().clamp(0, 100),
            )
          : null,
      sizeBytes: _asPositiveInt(raw['sizeBytes']),
      isOptimized: raw['isOptimized'] == true,
      canOptimize: raw['canOptimize'] == true,
    );
  }

  /// A byte count that is actually a byte count. Anything else — a string, a
  /// negative, a zero — reads as UNKNOWN, because a size of "0 B" on a model
  /// that plainly exists is worse than no size at all.
  static int? _asPositiveInt(Object? raw) {
    if (raw is! num) return null;
    final value = raw.round();
    return value > 0 ? value : null;
  }

  /// `{sourceBytes, outputBytes}` → whole-percent saving, or null when either
  /// number is missing or the "saving" is not one.
  static int? _savingPercent(Object? raw) {
    if (raw is! Map) return null;
    final source = _asPositiveInt(raw['sourceBytes']);
    final output = _asPositiveInt(raw['outputBytes']);
    if (source == null || output == null || output >= source) return null;
    return ((source - output) * 100 / source).round();
  }
}

/// A generation the OWNER is currently waiting on — `GET /projects/:id`'s
/// `generation`. Mirrors the backend's OwnerGenerationDto.
///
/// Deliberately NOT folded into [ProjectModelView]: a project can hold a
/// finished model AND a newer generation at the same time, and the finished one
/// must stay on screen while the new one runs. They are two independent facts,
/// so they are two independent objects.
class OwnerGenerationView {
  const OwnerGenerationView({
    required this.id,
    required this.status,
    required this.isAutoGenerated,
    this.progressPercent,
  });

  final String id;
  final ModelStatus status;

  /// True when nobody asked for this — it started when the capture finished.
  final bool isAutoGenerated;

  /// Coarse 0–100 when the worker has reported any. The owner sees only the
  /// number: the phase names describe our pipeline internals and mean nothing
  /// to someone who just wants to know how long they are waiting.
  final int? progressPercent;

  bool get isPending => status.isPending;
  bool get hasFailed => status == ModelStatus.failed;

  static OwnerGenerationView? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    if (id.isEmpty) return null;
    final percent = raw['progressPercent'];
    return OwnerGenerationView(
      id: id,
      status: ModelStatus.parse(raw['status']),
      isAutoGenerated: raw['isAutoGenerated'] == true,
      progressPercent: percent is num ? percent.round().clamp(0, 100) : null,
    );
  }
}
