// lib/domain/entities/project_model.dart
//
// Typed model of one 3D-model GENERATION record, as both the staff surface
// (`/admin/projects/:id/models`) and the owner surface (`GET /projects/:id`'s
// `model`) return it. Hand-synced with the backend's ProjectModelDto /
// OwnerModelDto (recapture-api/src/services/projectModelsService.ts) — there is
// no shared package, so a change on either side must be mirrored here.
//
// The staff and owner payloads differ deliberately: the owner one carries no
// keys, no selection and no staff actor ids. This entity models the UNION and
// leaves the staff-only fields null when parsed from the owner shape.
import 'generation_trace.dart';

/// Where the model came from. Drives the "Created by Meshy AI" badge — the badge
/// is never inferred from anything else.
enum ModelSource {
  meshy,
  manual,
  /// A source this build does not know (server ahead of the app). Renders
  /// unbadged rather than crashing the viewer.
  unknown;

  static ModelSource parse(Object? raw) => switch (raw.toString()) {
        'meshy' => ModelSource.meshy,
        'manual' => ModelSource.manual,
        _ => ModelSource.unknown,
      };

  /// The origin label shown on the viewer, or null when there is nothing to
  /// attribute.
  String? get badgeLabel => switch (this) {
        ModelSource.meshy => 'Created by Maya AI',
        ModelSource.manual || ModelSource.unknown => null,
      };
}

/// The badge shown on an AUTOMATICALLY generated model.
///
/// Deliberately says "preview quality": a model built from four auto-selected
/// photos is good, not finished. Presented as a product it disappoints;
/// presented as an AI preview it delights, and it makes the Regenerate
/// affordance next to it read as an invitation rather than an apology.
const String kAutoGeneratedBadgeLabel = 'AI generated — preview quality';

/// WHICH RENDITION of a generation a list entry describes.
///
/// One generation can arrive as TWO entries sharing the SAME `id` — the
/// untouched Meshy build and the web-optimized one — so staff can compare them.
/// That is a view of one record, not two models: there is still exactly one
/// paid generation behind them, which is why the ids match. Never dedupe a
/// model list by id.
enum ModelVariant {
  /// Meshy's output exactly as re-hosted. Always present.
  original,

  /// The web-optimized build: WebP textures + meshopt geometry.
  web,

  /// A rendition this build does not know (server ahead of the app). Renders
  /// unbadged rather than guessing.
  unknown;

  static ModelVariant parse(Object? raw) => switch (raw?.toString()) {
        // Absent means an older backend that had no variants at all — those
        // payloads only ever described the original.
        'original' || null => ModelVariant.original,
        'web' => ModelVariant.web,
        _ => ModelVariant.unknown,
      };

  /// The short pill shown on a history row. Null for the original, which is the
  /// baseline and needs no badge — badging both would be noise, not a signal.
  String? get badgeLabel => switch (this) {
        ModelVariant.web => 'OPT',
        ModelVariant.original || ModelVariant.unknown => null,
      };
}

/// One rendition's weight, so two entries can be compared without opening a
/// 3D tool. Every field is optional-by-absence at the source: a model whose
/// optimization has not run has no measurements at all.
class ModelMetrics {
  const ModelMetrics({
    required this.bytes,
    required this.triangles,
    required this.textureCount,
    required this.largestTextureBytes,
  });

  final int bytes;
  final int triangles;
  final int textureCount;
  final int largestTextureBytes;

  /// Compact "7.92 MB" / "318 KB". Hand-rolled for the same reason as the date
  /// stamp — one formatter does not justify a dependency.
  String get sizeLabel {
    if (bytes >= 1000000) return '${(bytes / 1000000).toStringAsFixed(2)} MB';
    if (bytes >= 1000) return '${(bytes / 1000).round()} KB';
    return '$bytes B';
  }

  /// Returns null rather than a zeroed instance when the payload has no
  /// metrics: an unknown size must never render as "0 B", which would read as
  /// a spectacular fake saving.
  static ModelMetrics? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final bytes = _int(raw['bytes']);
    if (bytes == null) return null;
    return ModelMetrics(
      bytes: bytes,
      triangles: _int(raw['triangles']) ?? 0,
      textureCount: _int(raw['textureCount']) ?? 0,
      largestTextureBytes: _int(raw['largestTextureBytes']) ?? 0,
    );
  }

  static int? _int(Object? raw) => switch (raw) {
        final int v => v,
        final num v => v.round(),
        _ => null,
      };
}

/// Generation lifecycle. `QUEUED`/`PROCESSING` are the polling states.
enum ModelStatus {
  queued,
  processing,
  succeeded,
  failed,
  /// Unknown to this build — treated as terminal so polling can't spin forever.
  unknown;

  static ModelStatus parse(Object? raw) => switch (raw.toString()) {
        'QUEUED' => ModelStatus.queued,
        'PROCESSING' => ModelStatus.processing,
        'SUCCEEDED' => ModelStatus.succeeded,
        'FAILED' => ModelStatus.failed,
        _ => ModelStatus.unknown,
      };

  /// Whether a generation in this state is still expected to change — the
  /// polling loop's stop condition.
  bool get isPending => this == ModelStatus.queued || this == ModelStatus.processing;
}

/// What the backend worker is doing RIGHT NOW inside a PROCESSING record.
/// Mirrors ProjectModelDto's `progress.phase`. Display-only.
enum ModelProgressPhase {
  /// Presigning the selected photos / submitting the Meshy task.
  preparing,
  /// Meshy is building the model — [ModelProgress.percent] is Meshy's own 0–100.
  generating,
  /// Downloading Meshy's results and re-hosting them on our S3.
  finalizing,
  /// A phase this build does not know (server ahead of the app). Renders as a
  /// generic "working…" step rather than crashing or hiding progress.
  unknown;

  static ModelProgressPhase parse(Object? raw) => switch (raw.toString()) {
        'PREPARING' => ModelProgressPhase.preparing,
        'GENERATING' => ModelProgressPhase.generating,
        'FINALIZING' => ModelProgressPhase.finalizing,
        _ => ModelProgressPhase.unknown,
      };
}

/// Live sub-status of a pending generation — the staff progress UI's data.
/// Staff payload only, and OPTIONAL: an older backend (or a record written
/// before the field existed) simply has none, and the UI falls back to the
/// phase-less copy it showed before.
class ModelProgress {
  const ModelProgress({required this.phase, required this.percent});

  final ModelProgressPhase phase;

  /// 0–100 within [phase]; clamped so a malformed payload can't overflow a
  /// progress bar.
  final int percent;

  static ModelProgress? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final percent = raw['percent'];
    return ModelProgress(
      phase: ModelProgressPhase.parse(raw['phase']),
      percent: percent is num ? percent.round().clamp(0, 100) : 0,
    );
  }
}

/// Why a generation failed. Mirrors ProjectModelDto's `error`.
///
/// [message] is SAFE to display: the backend contract is that meshyClient never
/// interpolates a response body or a presigned URL into one. Staff payload only.
class ModelError {
  const ModelError({required this.code, required this.message});

  final String code;
  final String message;

  static ModelError? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final message = (raw['message'] ?? '').toString();
    if (message.isEmpty) return null;
    return ModelError(code: (raw['code'] ?? '').toString(), message: message);
  }
}

/// One generation attempt.
class ProjectModelView {
  const ProjectModelView({
    required this.id,
    required this.source,
    required this.status,
    this.glbUrl,
    this.usdzUrl,
    this.previewUrl,
    this.approved = false,
    this.selectedKeys = const [],
    this.createdAt,
    this.error,
    this.progress,
    this.isAutoGenerated = false,
    this.generationTrace,
    this.variant = ModelVariant.original,
    this.isActiveVariant = true,
    this.metrics,
    this.optimizationPending = false,
  });

  final String id;
  final ModelSource source;
  final ModelStatus status;

  /// Whether the backend generated this itself after the capture finished,
  /// with no human choosing photos. Drives [kAutoGeneratedBadgeLabel] and the
  /// Regenerate affordance. Defaults false so a payload from an older backend
  /// (or the staff shape, which never sets it) reads as human-requested.
  final bool isAutoGenerated;

  /// Our CloudFront GLB URL — non-null exactly when [status] is succeeded.
  final String? glbUrl;

  /// Our CloudFront USDZ URL — iOS AR Quick Look's format. An AR enhancement
  /// only: Meshy doesn't always produce one, so it never gates [isViewable].
  final String? usdzUrl;
  final String? previewUrl;

  /// Whether staff signed off on this model ("no manual creation needed").
  final bool approved;

  /// The photos this attempt used. Staff payload only — empty for an owner.
  final List<String> selectedKeys;

  /// When the attempt was requested — how the history labels its rows (an index
  /// would renumber itself as new generations land at the head of the list).
  /// Null when the timestamp is absent or malformed.
  final DateTime? createdAt;

  /// The failure, for a FAILED record. Staff payload only — the owner endpoint
  /// never returns a failed attempt, so [tryFromOwnerMap] never parses this.
  final ModelError? error;

  /// Live worker sub-status while [status] is pending. Staff payload only, and
  /// null whenever the backend hasn't reported one (older server, QUEUED record,
  /// terminal record) — the UI must always have a phase-less fallback.
  final ModelProgress? progress;

  /// How this generation was decided — the server's request steps and the photo
  /// selector's counters. STAFF payload only, and null for every record written
  /// before the trace existed, so any reader must treat it as absent-by-default.
  final GenerationTrace? generationTrace;

  /// Which rendition this entry describes. Defaults to [ModelVariant.original]
  /// so a payload from a backend that predates the optimization pipeline — and
  /// the owner shape, which never sends it — reads as the untouched model.
  final ModelVariant variant;

  /// Whether this is the rendition owners are currently served. Exactly one of
  /// a generation's entries is active at a time, and it is an ADMIN's choice:
  /// producing an optimized build never promotes it. Defaults true so a
  /// single-entry payload is never rendered as "not being used".
  final bool isActiveVariant;

  /// This rendition's weight, once the optimization pipeline has measured it.
  /// Null for every record generated before the pipeline existed.
  final ModelMetrics? metrics;

  /// Whether the web-optimization job for this generation is still queued or
  /// running — i.e. this model is SUCCEEDED but not yet FINISHED.
  ///
  /// The distinction is the whole reason this field exists. Generation and
  /// optimization are two backend jobs, and for the minute between them the
  /// URLs above still point at the untouched original: the 200k-triangle build
  /// that the WebView often cannot load. A surface that treats
  /// [ModelStatus.succeeded] as "done" opens exactly that model and never
  /// revisits it.
  ///
  /// Defaults false so a payload from a backend that predates the flag — or a
  /// record generated before the pipeline existed, which will never be
  /// optimized — reads as settled rather than waiting forever.
  final bool optimizationPending;

  /// True when this row is the optimized build — the one worth badging.
  bool get isOptimized => variant == ModelVariant.web;

  bool get isViewable => status == ModelStatus.succeeded && glbUrl != null;

  /// A model that is both viewable AND final: nothing is still going to change
  /// which bytes [glbUrl] resolves to. What "ready to show the user" means.
  bool get isSettled => isViewable && !optimizationPending;

  /// Parses the STAFF shape (`/admin/projects/:id/models` items), where the
  /// URLs live under `artifacts`.
  static ProjectModelView? tryFromStaffMap(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    if (id.isEmpty) return null;
    final artifacts = raw['artifacts'];
    return ProjectModelView(
      id: id,
      source: ModelSource.parse(raw['source']),
      status: ModelStatus.parse(raw['status']),
      glbUrl: artifacts is Map ? artifacts['glb'] as String? : null,
      usdzUrl: artifacts is Map ? artifacts['usdz'] as String? : null,
      previewUrl: artifacts is Map ? artifacts['preview'] as String? : null,
      approved: raw['approved'] != null,
      selectedKeys: [
        if (raw['selectedKeys'] case final List keys)
          for (final k in keys) k.toString(),
      ],
      // A malformed timestamp yields null rather than throwing — a history row
      // that can't be labelled is still worth showing.
      createdAt: DateTime.tryParse((raw['createdAt'] ?? '').toString()),
      error: ModelError.tryParse(raw['error']),
      progress: ModelProgress.tryParse(raw['progress']),
      generationTrace: GenerationTrace.tryParse(raw['generationTrace']),
      variant: ModelVariant.parse(raw['variant']),
      // Absent reads as active: an older backend sent one entry per generation,
      // and that entry was by definition the one being served.
      isActiveVariant: raw['isActiveVariant'] != false,
      metrics: ModelMetrics.tryParse(raw['metrics']),
      // Absent reads as settled — an older backend sent no flag and had no
      // second job to wait for.
      optimizationPending: raw['optimizationPending'] == true,
    );
  }

  /// Parses the OWNER shape (`GET /projects/:id` → `model`), which is flat and
  /// only ever describes a finished model.
  static ProjectModelView? tryFromOwnerMap(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    final glb = (raw['glbUrl'] ?? '').toString();
    if (id.isEmpty || glb.isEmpty) return null;
    return ProjectModelView(
      id: id,
      source: ModelSource.parse(raw['source']),
      // The owner endpoint only ever returns a SUCCEEDED model.
      status: ModelStatus.succeeded,
      glbUrl: glb,
      usdzUrl: raw['usdzUrl'] as String?,
      previewUrl: raw['previewUrl'] as String?,
      approved: raw['approved'] == true,
      isAutoGenerated: raw['isAutoGenerated'] == true,
      optimizationPending: raw['optimizationPending'] == true,
      createdAt: DateTime.tryParse((raw['createdAt'] ?? '').toString()),
      // NO `error` here, deliberately: the owner endpoint only ever returns a
      // SUCCEEDED model, so parsing one would only invite leaking a failure
      // (and the staff copy that goes with it) onto the owner's surface.
    );
  }
}

/// A generation the OWNER is currently waiting on — `GET /projects/:id`'s
/// `generation`. Mirrors the backend's OwnerGenerationDto.
///
/// Deliberately NOT folded into [ProjectModelView]: a project can hold a
/// finished model AND a newer generation at the same time, and the finished one
/// must stay on screen while the new one runs. They are two independent facts,
/// so they are two independent objects.
class OwnerGenerationView {
  const OwnerGenerationView({
    required this.id,
    required this.status,
    required this.isAutoGenerated,
    this.progressPercent,
  });

  final String id;
  final ModelStatus status;

  /// True when nobody asked for this — it started when the capture finished.
  final bool isAutoGenerated;

  /// Coarse 0–100 when the worker has reported any. The owner sees only the
  /// number: the phase names describe our pipeline internals and mean nothing
  /// to someone who just wants to know how long they are waiting.
  final int? progressPercent;

  bool get isPending => status.isPending;
  bool get hasFailed => status == ModelStatus.failed;

  static OwnerGenerationView? tryParse(Object? raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    if (id.isEmpty) return null;
    final percent = raw['progressPercent'];
    return OwnerGenerationView(
      id: id,
      status: ModelStatus.parse(raw['status']),
      isAutoGenerated: raw['isAutoGenerated'] == true,
      progressPercent: percent is num ? percent.round().clamp(0, 100) : null,
    );
  }
}
