// lib/presentation/screens/capture/capture_summary_screen.dart
//
// Screen 6C-Complete — the "Capture complete" summary shown after all guided
// capture levels (A/B/C) finish. It is READ-ONLY over capture data: one card per
// configured level (generated by iterating CaptureLevel.values, never hardcoded),
// each card showing the level's real captured-frame count, a representative
// thumbnail (same ledger source the review grids use), and a complete/incomplete
// status. Continue advances to the next phase (gated on all levels complete);
// Review returns to the review flow (global, plus per-card entry).
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../app/routes/app_router.dart';
import '../../../app/theme/app_colors.dart';
import '../../../app/theme/app_spacing.dart';
import '../../../application/capture/analytics/capture_level_events.dart';
import '../../../application/capture/analytics/capture_level_session.dart';
import '../../../application/capture/capture_summary_provider.dart';
import '../../../application/capture/completion_gate_provider.dart';
import '../../../application/capture/review_grid_items_provider.dart';
import '../../../utils/analytics.dart';
import '../../widgets/app_button.dart';
import '../../widgets/app_card.dart';

/// The review grid route for a level (per-card / global Review entry).
String _reviewRouteForLevel(CaptureLevel level) => switch (level) {
      CaptureLevel.a => AppRoutes.levelAReview,
      CaptureLevel.b => AppRoutes.levelBReview,
      CaptureLevel.c => AppRoutes.levelCReview,
    };

class CaptureSummaryScreen extends ConsumerStatefulWidget {
  const CaptureSummaryScreen({super.key});

  @override
  ConsumerState<CaptureSummaryScreen> createState() =>
      _CaptureSummaryScreenState();
}

class _CaptureSummaryScreenState extends ConsumerState<CaptureSummaryScreen> {
  /// Single-shot guard so a rapid double-tap on Continue advances only once.
  bool _continued = false;

  static String get _deviceType =>
      defaultTargetPlatform == TargetPlatform.iOS ? 'ios' : 'android';

  /// The opaque funnel session id, or '' when no session was observed (app
  /// restart / deep-link) — the same accepted edge the rest of the funnel uses;
  /// never throws, never starts a new session.
  String get _sessionId =>
      ref.read(captureLevelSessionProvider)?.sessionId ?? '';

  @override
  void initState() {
    super.initState();
    // Once per entry (never on rebuild): the summary became visible. Counts come
    // from the single completion gate, not a local rule.
    final gate = ref.read(completionGateProvider);
    Analytics.logEvent(AnalyticsEvents.captureSummaryViewed, {
      'phase': 'guided_capture',
      'session_id': _sessionId,
      'levels_complete': gate.levelsComplete,
      'levels_total': gate.levelsTotal,
      'device_type': _deviceType,
    });
  }

  /// Recompute the summary from the (possibly re-captured) ledger after a Review
  /// round-trip: the per-level item providers are kept alive by this screen's
  /// watch, so force them — and the aggregate — to recompute.
  void _refreshAfterReview() {
    for (final level in CaptureLevel.values) {
      ref.invalidate(reviewGridItemsProvider(pitchBandIdForLevel(level)));
    }
    ref.invalidate(captureSummaryProvider);
  }

  void _onContinue(bool allComplete) {
    if (_continued) return;
    _continued = true;
    Analytics.logEvent(AnalyticsEvents.captureSummaryAction, {
      'phase': 'guided_capture',
      'session_id': _sessionId,
      'action': 'continue',
      'all_complete': allComplete,
      'device_type': _deviceType,
    });
    context.go(AppRoutes.uploading);
  }

  /// Global Review (no level) or a per-card review (with [level]). Routes to the
  /// review grid and refreshes the cards on return.
  Future<void> _onReview({CaptureLevel? level}) async {
    Analytics.logEvent(AnalyticsEvents.captureSummaryAction, {
      'phase': 'guided_capture',
      'session_id': _sessionId,
      'action': 'review',
      if (level != null) 'level': level.code,
      'device_type': _deviceType,
    });
    final target = level ?? CaptureLevel.values.first;
    await context.push(_reviewRouteForLevel(target));
    if (mounted) _refreshAfterReview();
  }

  @override
  Widget build(BuildContext context) {
    final summaries = ref.watch(captureSummaryProvider);
    // The SINGLE gate drives Continue + per-card status (no local rule). Reaching
    // this screen unlocked is the locked→unlocked transition for the milestone.
    final gate = ref.watch(completionGateProvider);
    final allComplete = gate.isUnlocked;
    ref
        .read(summaryGateAnalyticsProvider.notifier)
        .syncUnlockMilestone(gate, sessionId: _sessionId);

    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        automaticallyImplyLeading: false,
        title: Text('Capture complete',
            style: Theme.of(context).textTheme.titleLarge),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(AppSpacing.lg),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Review each level, then continue.',
                    style: Theme.of(context).textTheme.bodyMedium,
                  ),
                  const SizedBox(height: AppSpacing.xl),
                  // One card per configured level (iterates CaptureLevel.values).
                  for (final s in summaries)
                    Padding(
                      padding: const EdgeInsets.only(bottom: AppSpacing.sm),
                      child: _LevelSummaryCard(
                        summary: s,
                        // Per-card status from the SAME gate as Continue.
                        complete: gate.isLevelComplete(s.level.code),
                        onReview: () => _onReview(level: s.level),
                      ),
                    ),
                ],
              ),
            ),
          ),
          _BottomBar(
            allComplete: allComplete,
            onContinue: () => _onContinue(allComplete),
            onReview: () => _onReview(),
          ),
        ],
      ),
    );
  }
}

class _BottomBar extends StatelessWidget {
  const _BottomBar({
    required this.allComplete,
    required this.onContinue,
    required this.onReview,
  });

  final bool allComplete;
  final VoidCallback onContinue;
  final VoidCallback onReview;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: AppColors.bgPrimary,
      child: SafeArea(
        top: false,
        child: Padding(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              if (!allComplete) ...[
                Text(
                  'Complete all levels to continue.',
                  key: const Key('continue_gate_reason'),
                  style: Theme.of(context)
                      .textTheme
                      .bodySmall
                      ?.copyWith(color: AppColors.textMuted),
                ),
                const SizedBox(height: AppSpacing.sm),
              ],
              AppButton(
                key: const Key('summary_continue'),
                label: 'Continue',
                // Null disables the button → never silently advances incomplete.
                onPressed: allComplete ? onContinue : null,
              ),
              const SizedBox(height: AppSpacing.sm),
              AppButton.secondary(
                key: const Key('summary_review'),
                label: 'Review',
                onPressed: onReview,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _LevelSummaryCard extends StatelessWidget {
  const _LevelSummaryCard({
    required this.summary,
    required this.complete,
    required this.onReview,
  });

  final LevelCaptureSummary summary;

  /// Per-level completeness from the completion gate (single source of truth).
  final bool complete;
  final VoidCallback onReview;

  @override
  Widget build(BuildContext context) {
    return AppCard(
      // Tapping the card reviews this level (per-card review entry).
      onTap: onReview,
      child: Row(
        children: [
          _Thumb(path: summary.thumbnailPath),
          const SizedBox(width: AppSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Level ${summary.level.code} • ${summary.name}',
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
                const SizedBox(height: AppSpacing.xs),
                Text(
                  complete
                      ? '${summary.frameCount} frames'
                          '${summary.warnedCount > 0 ? ' • ${summary.warnedCount} warned' : ''}'
                      : 'No frames captured',
                  style: Theme.of(context)
                      .textTheme
                      .bodySmall
                      ?.copyWith(color: AppColors.textMuted),
                ),
              ],
            ),
          ),
          const SizedBox(width: AppSpacing.sm),
          _StatusChip(complete: complete),
        ],
      ),
    );
  }
}

/// Status pill: complete (check) vs incomplete (alert), using design tokens only.
class _StatusChip extends StatelessWidget {
  const _StatusChip({required this.complete});

  final bool complete;

  @override
  Widget build(BuildContext context) {
    final color = complete ? AppColors.success : AppColors.warning;
    return Semantics(
      label: complete ? 'Complete' : 'Incomplete',
      excludeSemantics: true,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(complete ? Icons.check_circle : Icons.error_outline,
              color: color, size: 18),
          const SizedBox(width: AppSpacing.xs),
          Text(
            complete ? 'Complete' : 'Incomplete',
            style: Theme.of(context)
                .textTheme
                .bodySmall
                ?.copyWith(color: color, fontWeight: FontWeight.w600),
          ),
        ],
      ),
    );
  }
}

/// Square representative thumbnail, downscale-decoded (same mechanism as the
/// review grid). A missing path or a decode failure degrades to a neutral
/// placeholder — never a crash.
class _Thumb extends StatelessWidget {
  const _Thumb({required this.path});

  final String? path;

  static const double _size = 56;

  @override
  Widget build(BuildContext context) {
    final radius = BorderRadius.circular(AppRadius.xs);
    final dpr = MediaQuery.devicePixelRatioOf(context);
    final placeholder = DecoratedBox(
      decoration: BoxDecoration(color: AppColors.surface2, borderRadius: radius),
      child: const Center(
        child: Icon(Icons.photo_outlined,
            size: 22, color: AppColors.textMuted),
      ),
    );

    return SizedBox(
      width: _size,
      height: _size,
      child: path == null
          ? placeholder
          : ClipRRect(
              borderRadius: radius,
              child: Image.file(
                File(path!),
                fit: BoxFit.cover,
                cacheWidth: (_size * dpr).round(),
                gaplessPlayback: true,
                errorBuilder: (_, __, ___) => placeholder,
              ),
            ),
    );
  }
}
