// test/dev_probe/bundle_disk_store_test.dart
//
// BundleDiskStore against a real temp directory (rootProvider seam — no
// path_provider plugin in tests): write lays the capture-shaped tree
// (images/{RING}/… + capture_manifest.json) under one run folder, read
// returns the exact bytes, totalSizeBytes sums every run, clear removes the
// whole root.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:recapture/dev/dev_probe/bundle_disk_store.dart';
import 'package:recapture/dev/dev_probe/dummy_bundle.dart';

void main() {
  const keyPrefix = 'development/u1/p1/j1/';
  const manifestKey = '${keyPrefix}capture_manifest.json';

  late Directory tempRoot;
  late BundleDiskStore store;

  setUp(() {
    tempRoot = Directory.systemTemp.createTempSync('dev_probe_store_test');
    store = BundleDiskStore(rootProvider: () async => tempRoot);
  });

  tearDown(() {
    if (tempRoot.existsSync()) tempRoot.deleteSync(recursive: true);
  });

  test('write lays out the bundle like a real capture and read round-trips',
      () async {
    final bundle =
        buildDummyBundle(keyPrefix: keyPrefix, manifestKey: manifestKey);
    final written = await store.write(bundle, keyPrefix: keyPrefix);

    expect(Directory(written.directory).existsSync(), isTrue);
    expect(written.pathsByKey, hasLength(kSmokeExpectedFilesCount));

    // Key → relative path mapping: prefix stripped, ring folders kept.
    final firstImagePath = written.pathFor('${keyPrefix}images/EYE/eye_0001.jpg');
    expect(firstImagePath, startsWith(written.directory));
    expect(
      firstImagePath.replaceAll(Platform.pathSeparator, '/'),
      endsWith('images/EYE/eye_0001.jpg'),
    );
    final manifestPath = written.pathFor(manifestKey);
    expect(
      manifestPath.replaceAll(Platform.pathSeparator, '/'),
      endsWith('/capture_manifest.json'),
    );

    // Every file exists on disk and read() returns the generated bytes.
    for (final file in bundle.files) {
      final path = written.pathFor(file.key);
      expect(File(path).existsSync(), isTrue, reason: file.key);
      expect(await store.read(path), file.bytes, reason: file.key);
    }

    expect(await store.totalSizeBytes(), bundle.totalBytes);
  });

  test('totalSizeBytes sums across runs; clear deletes the whole root',
      () async {
    final bundle =
        buildDummyBundle(keyPrefix: keyPrefix, manifestKey: manifestKey);
    // Back-to-back writes (possibly same millisecond) must land in distinct
    // run folders.
    await store.write(bundle, keyPrefix: keyPrefix);
    await store.write(bundle, keyPrefix: keyPrefix);

    expect(await store.totalSizeBytes(), bundle.totalBytes * 2);

    await store.clear();
    expect(tempRoot.existsSync(), isFalse);
    expect(await store.totalSizeBytes(), 0);

    // Idempotent on an already-clean root.
    await store.clear();
  });

  test('unknown key throws instead of uploading nothing', () async {
    final bundle =
        buildDummyBundle(keyPrefix: keyPrefix, manifestKey: manifestKey);
    final written = await store.write(bundle, keyPrefix: keyPrefix);
    expect(() => written.pathFor('not/a/real/key.jpg'), throwsStateError);
  });
}
