// test/catalog/product_model_picker_test.dart
//
// The model picker's two contracts that no other test can see.
//
//  1. PREVIEW IS NOT SELECT. Opening a model in the viewer and coming back must
//     leave the form exactly as it was — the selection, and every typed field.
//     If preview also selected, every comparison would change the answer, and
//     the user would have no way to look at a model without choosing it.
//
//  2. NO STAFF ROUTE, EVER. The owner list route and the staff one return
//     DIFFERENT payloads through different parsers, and an owner (or an admin
//     who does not own the capture) gets an identical 404 on `/admin`. Routing
//     around that would be the "second, weaker door" AGENTS.md forbids. This is
//     the contract that would break silently, so it is asserted at the WIRE:
//     the real repository runs over a fake Dio adapter that records every path.
import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:recapture/application/catalog/catalog_notifier.dart';
import 'package:recapture/application/projects/owner_model_history_notifier.dart';
import 'package:recapture/application/projects/projects_notifier.dart';
import 'package:recapture/data/repositories/catalog_products_repository.dart';
import 'package:recapture/application/auth/user_role_notifier.dart';
import 'package:recapture/data/repositories/live_projects_repository.dart';
import 'package:recapture/domain/entities/catalog.dart';
import 'package:recapture/domain/entities/catalog_product.dart';
import 'package:recapture/domain/entities/product_availability.dart';
import 'package:recapture/domain/entities/product_type.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/domain/entities/project_status.dart';
import 'package:recapture/presentation/screens/catalog/add_product_screen.dart';
import 'package:recapture/presentation/widgets/model_choice_tile.dart';

import 'catalog_entities_test.dart' as golden;

/// A stand-in for the 3D render surface: the real one drives a WebView, which
/// has no platform implementation in a widget test.
Widget _stubRender(BuildContext _, ProjectModelView model) =>
    Text('RENDER:${model.id}');

class _FakeProductsRepo implements CatalogProductsRepository {
  String? lastSourceModelId;
  int createCalls = 0;

  @override
  Future<CatalogProduct> create({
    required ProductType type,
    required String name,
    String? description,
    double? price,
    String? categoryId,
    List<String>? tags,
    ProductAvailability? availability,
    bool? featured,
    String? sourceModelId,
    String? imageKey,
  }) async {
    createCalls++;
    lastSourceModelId = sourceModelId;
    return CatalogProduct.fromMap(golden.productGolden()..['name'] = name);
  }

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnimplementedError('${invocation.memberName} is not used here');
}

class _StubProjects extends ProjectsNotifier {
  _StubProjects(this._projects);

  final List<Project> _projects;

  @override
  Future<List<Project>> build() async => _projects;
}

class _StubOwnerHistory extends OwnerModelHistoryNotifier {
  _StubOwnerHistory(this._models);

  final List<ProjectModelView> _models;

  @override
  Future<List<ProjectModelView>> build(String projectId) async => _models;
}

class _StubCatalog extends CatalogNotifier {
  @override
  Future<Catalog?> build() async => Catalog.fromMap(golden.catalogGolden());

  @override
  Future<void> refresh() async {}
}

/// Records every path the app asks for, and answers the owner model-list route.
class _RecordingAdapter implements HttpClientAdapter {
  final List<String> paths = [];

  @override
  void close({bool force = false}) {}

  @override
  Future<ResponseBody> fetch(
    RequestOptions options,
    Stream<Uint8List>? requestStream,
    Future<void>? cancelFuture,
  ) async {
    paths.add(options.path);
    return ResponseBody.fromString(
      jsonEncode({
        'status': 'success',
        'models': [
          {
            'id': 'm2',
            'source': 'meshy',
            'status': 'SUCCEEDED',
            'glbUrl': 'https://cdn.example/m2.glb',
            'createdAt': '2026-02-02T00:00:00.000Z',
            'approved': false,
            'isAutoGenerated': false,
            'isOptimized': false,
            'canOptimize': false,
          },
          {
            'id': 'm1',
            'source': 'meshy',
            'status': 'SUCCEEDED',
            'glbUrl': 'https://cdn.example/m1.glb',
            'createdAt': '2026-01-01T00:00:00.000Z',
            'approved': false,
            'isAutoGenerated': false,
            'isOptimized': false,
            'canOptimize': false,
          },
        ],
      }),
      200,
      headers: {
        Headers.contentTypeHeader: ['application/json'],
      },
    );
  }
}

Project _project(String id, String name) => Project(
      id: id,
      name: name,
      status: ProjectStatus.completed,
      updatedAt: DateTime(2026, 1, 1),
      modelCount: 2,
    );

ProjectModelView _model(String id) => ProjectModelView(
      id: id,
      source: ModelSource.meshy,
      status: ModelStatus.succeeded,
      glbUrl: 'https://cdn.example/$id.glb',
    );

Future<void> _pump(WidgetTester tester, Widget app) async {
  tester.view.physicalSize = const Size(1200, 3200);
  tester.view.devicePixelRatio = 1.0;
  addTearDown(tester.view.resetPhysicalSize);
  addTearDown(tester.view.resetDevicePixelRatio);
  await tester.pumpWidget(app);
  await tester.pumpAndSettle();
}

Future<void> _chooseCapture(WidgetTester tester, String name) async {
  await tester.tap(find.byType(DropdownButtonFormField<String>));
  await tester.pumpAndSettle();
  await tester.tap(find.text(name).last);
  await tester.pumpAndSettle();
}

void main() {
  testWidgets('preview opens the viewer and comes back with everything intact',
      (tester) async {
    final repo = _FakeProductsRepo();
    await _pump(
      tester,
      ProviderScope(
        overrides: [
          catalogProductsRepositoryProvider.overrideWithValue(repo),
          projectsProvider
              .overrideWith(() => _StubProjects([_project('p1', 'Vase')])),
          ownerModelHistoryProvider.overrideWith(
            () => _StubOwnerHistory([_model('m2'), _model('m1')]),
          ),
          catalogProvider.overrideWith(_StubCatalog.new),
          // The pushed viewer's Export button gates itself on this; left to the
          // real provider it would reach for Hive.
          isStaffProvider.overrideWithValue(false),
        ],
        child: const MaterialApp(
          home: AddProductScreen(renderBuilder: _stubRender),
        ),
      ),
    );

    await _chooseCapture(tester, 'Vase');
    await tester.enterText(
      find.widgetWithText(TextFormField, 'Product name'),
      'Blue vase',
    );
    await tester.pumpAndSettle();

    // Deliberately NOT the preselected newest — the point is that previewing
    // one model does not re-point the selection at it.
    await tester.tap(find.byKey(const ValueKey('model_choice_tile_m1')));
    await tester.pumpAndSettle();

    await tester.tap(
      find.descendant(
        of: find.byKey(const ValueKey('model_choice_tile_m2')),
        matching: find.text('Preview'),
      ),
    );
    await tester.pumpAndSettle();

    // The viewer is up, rendering the model whose Preview was pressed.
    expect(find.text('RENDER:m2'), findsOneWidget);
    // Its only affordances are look-and-leave: no Approve, no Optimize, no
    // Regenerate inside a product form.
    expect(find.text('Approve'), findsNothing);
    expect(find.text('Optimize'), findsNothing);
    expect(find.text('Regenerate'), findsNothing);

    await tester.pageBack();
    await tester.pumpAndSettle();

    // The typed name survived, and the selection is still the one that was
    // CHOSEN, not the one that was looked at.
    expect(find.text('Blue vase'), findsOneWidget);
    await tester.tap(find.widgetWithText(ElevatedButton, 'Add product'));
    await tester.pumpAndSettle();
    expect(repo.lastSourceModelId, 'm1');
  });

  testWidgets('reads the OWNER route and never touches /admin', (tester) async {
    final adapter = _RecordingAdapter();
    final dio = Dio(BaseOptions(baseUrl: 'https://api.example'))
      ..httpClientAdapter = adapter;
    final repo = _FakeProductsRepo();

    await _pump(
      tester,
      ProviderScope(
        overrides: [
          catalogProductsRepositoryProvider.overrideWithValue(repo),
          projectsProvider
              .overrideWith(() => _StubProjects([_project('p1', 'Vase')])),
          // The REAL repository over a fake wire: the assertion below is about
          // the request that actually goes out, not about which method a stub
          // happened to be asked for.
          liveProjectsRepositoryProvider
              .overrideWithValue(RemoteLiveProjectsRepository(dio)),
          catalogProvider.overrideWith(_StubCatalog.new),
        ],
        child: const MaterialApp(home: AddProductScreen()),
      ),
    );

    await _chooseCapture(tester, 'Vase');

    // The owner list route, parsed through the owner parser — two tiles, and
    // the newest preselected.
    expect(find.byType(ModelChoiceTile), findsNWidgets(2));
    expect(adapter.paths, contains('/projects/p1/models'));
    expect(
      adapter.paths.where((p) => p.contains('/admin')),
      isEmpty,
      reason: 'An owner gets an identical 404 on the staff route by design; '
          'routing around that would be a second, weaker door.',
    );
  });
}
