// test/projects/generation_tracker_test.dart
//
// The app-scoped generation tracker: the state machine, the poll loop, the
// suppression seam that keeps it off ModelBuildingScreen's endpoint, and the
// capture-lock predicate derived from it.
//
// TIMER DISCIPLINE: the tracker is app-scoped and NOT autoDisposed, so any test
// that leaves it with a running entry leaves a pending cadence timer behind and
// fails with "A Timer is still pending". Every harness therefore registers
// `container.dispose` as a tear-down, which cancels both the cadence timer and
// any success-linger timer.
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:recapture/application/auth/auth_notifier.dart';
import 'package:recapture/application/projects/generation_tracker_notifier.dart';
import 'package:recapture/data/local/generation_tracker_box.dart';
import 'package:recapture/data/local/projects_cache_box.dart';
import 'package:recapture/data/local/storage_providers.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/auth_state.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/utils/analytics.dart';

import 'repo_fake_defaults.dart';

// ── Fakes ────────────────────────────────────────────────────────────────────

/// A repository whose model state per project is scripted by the test, and
/// which counts every call so "who polled what, how often" is assertable.
class _FakeRepo with FakeProjectModelDefaults implements ProjectsRepository {
  final Map<String, OwnerModelState> states = {};
  final Map<String, int> calls = {};

  /// Projects whose fetch should blow up (transient network failure).
  final Set<String> throwFor = {};

  int callsFor(String id) => calls[id] ?? 0;
  int get totalCalls => calls.values.fold(0, (a, b) => a + b);

  @override
  Future<OwnerModelState> fetchModelState(String id) async {
    calls[id] = (calls[id] ?? 0) + 1;
    if (throwFor.contains(id)) throw Exception('transient');
    return states[id] ?? const OwnerModelState();
  }

  @override
  Future<List<Project>> list() async => const [];

  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> rename(String id, String newName) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> delete(String id, {String? confirmName}) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> retry(String id) async =>
      throw UnimplementedError('not used here');
}

/// In-memory stand-in for the Hive gateway — real persistence is exercised in
/// generation_tracker_box_test.dart, against a real temp-dir box.
class _FakeStore implements GenerationTrackerStore {
  _FakeStore([this.seeded = const []]);

  List<TrackedGenerationRecord> seeded;
  List<TrackedGenerationRecord> saved = const [];
  int saveCount = 0;
  bool readThrows = false;

  @override
  Future<List<TrackedGenerationRecord>> read() async {
    if (readThrows) throw Exception('unreadable');
    return seeded;
  }

  @override
  Future<void> save(List<TrackedGenerationRecord> records) async {
    saveCount++;
    saved = records;
  }

  @override
  Future<void> clear() async => saved = const [];
}

/// Settling a generation invalidates [projectsProvider] — which builds
/// ProjectsNotifier, which reads the projects CACHE box. Correct in production;
/// here it just means the harness has to fake that box too, or every terminal
/// transition would try to open real Hive.
class _FakeProjectsCacheBox implements ProjectsCacheBox {
  @override
  Future<CachedProjects?> read() async => null;

  @override
  Future<void> save(List<Project> projects) async {}

  @override
  Future<void> clear() async {}
}

class _FakeAuthNotifier extends AuthNotifier {
  @override
  AuthState build() => const AuthRestoring();

  void emit(AuthState next) => state = next;
}

// ── Builders ────────────────────────────────────────────────────────────────

OwnerModelState _running({int? percent}) => OwnerModelState(
      generation: OwnerGenerationView(
        id: 'gen-1',
        status: ModelStatus.processing,
        isAutoGenerated: true,
        progressPercent: percent,
      ),
    );

OwnerModelState get _failed => const OwnerModelState(
      generation: OwnerGenerationView(
        id: 'gen-1',
        status: ModelStatus.failed,
        isAutoGenerated: true,
      ),
    );

OwnerModelState get _succeeded => OwnerModelState(
      model: ProjectModelView(
        id: 'model-1',
        source: ModelSource.meshy,
        status: ModelStatus.succeeded,
        glbUrl: 'https://cdn.example.com/model.glb',
        isAutoGenerated: true,
      ),
    );

typedef _Harness = ({
  ProviderContainer container,
  _FakeRepo repo,
  _FakeStore store,
  _FakeAuthNotifier auth,
});

_Harness _harness({_FakeStore? store}) {
  final repo = _FakeRepo();
  final theStore = store ?? _FakeStore();
  final auth = _FakeAuthNotifier();
  final container = ProviderContainer(overrides: [
    projectsRepositoryProvider.overrideWithValue(repo),
    generationTrackerStoreProvider.overrideWithValue(theStore),
    projectsCacheBoxProvider.overrideWithValue(_FakeProjectsCacheBox()),
    authProvider.overrideWith(() => auth),
  ]);
  // Cancels the cadence timer AND any success-linger timer — see the file note.
  addTearDown(container.dispose);
  return (container: container, repo: repo, store: theStore, auth: auth);
}

GenerationTrackerNotifier _tracker(_Harness h) =>
    h.container.read(generationTrackerProvider.notifier);

GenerationTrackerState _state(_Harness h) =>
    h.container.read(generationTrackerProvider);

void main() {
  // AppLifecycleListener (built in the notifier) needs a binding.
  TestWidgetsFlutterBinding.ensureInitialized();

  tearDown(() => Analytics.testSink = null);

  group('track', () {
    test('adds a running entry named for the project', () {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');

      final entry = _state(h).generations['p1'];
      expect(entry, isNotNull);
      expect(entry!.projectName, 'Chair');
      expect(entry.status, TrackedGenerationStatus.running);
      expect(entry.percent, isNull);
    });

    test('falls back to a neutral name rather than a wrong one', () {
      final h = _harness();
      _tracker(h).track('p1');
      expect(_state(h).generations['p1']!.projectName, kUnnamedTrackedProject);
    });

    test('is idempotent — a second track is a no-op, not a second entry', () {
      final h = _harness();
      final events = <String>[];
      Analytics.testSink = (name, _) => events.add(name);

      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).track('p1', projectName: 'Something else');

      expect(_state(h).generations, hasLength(1));
      // The first name survives; the second call changed nothing at all.
      expect(_state(h).generations['p1']!.projectName, 'Chair');
      expect(events.where((e) => e == 'generation_tracking_started'),
          hasLength(1));
    });

    test('emits the started event with its source', () {
      final h = _harness();
      final props = <Map<String, Object?>>[];
      Analytics.testSink = (name, p) {
        if (name == 'generation_tracking_started') props.add(p);
      };

      _tracker(h).track('p1', source: GenerationTrackingSource.postCapture);
      expect(props.single['source'], 'post_capture');
    });

    test('an empty id is ignored rather than tracked as a phantom', () {
      final h = _harness();
      _tracker(h).track('');
      expect(_state(h).isEmpty, isTrue);
    });
  });

  group('poll → terminal transitions', () {
    test('a viewable model settles as succeeded', () async {
      final h = _harness();
      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');

      await _tracker(h).debugTick();

      expect(
        _state(h).generations['p1']!.status,
        TrackedGenerationStatus.succeeded,
      );
    });

    test('a failed generation settles as failed', () async {
      final h = _harness();
      h.repo.states['p1'] = _failed;
      _tracker(h).track('p1', projectName: 'Chair');

      await _tracker(h).debugTick();

      expect(
          _state(h).generations['p1']!.status, TrackedGenerationStatus.failed);
    });

    test('the poll cap settles everything still running as gave-up', () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 10);
      _tracker(h).track('p1', projectName: 'Chair');

      // Well past the cap; the guard fires on the first schedule that sees it.
      for (var i = 0; i < 121; i++) {
        await _tracker(h).debugTick();
      }

      expect(
          _state(h).generations['p1']!.status, TrackedGenerationStatus.givenUp);
      // And it stopped asking — that is the whole point of the cap.
      final callsAtCap = h.repo.callsFor('p1');
      await _tracker(h).debugTick();
      expect(h.repo.callsFor('p1'), callsAtCap);
    });

    test('a settled entry is never re-polled or re-settled', () async {
      final h = _harness();
      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');
      await _tracker(h).debugTick();

      final calls = h.repo.callsFor('p1');
      await _tracker(h).debugTick();
      expect(h.repo.callsFor('p1'), calls);
    });

    test('a transient fetch failure keeps the run alive for the next tick',
        () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 20);
      h.repo.throwFor.add('p1');
      _tracker(h).track('p1', projectName: 'Chair');

      await _tracker(h).debugTick();
      // NOT failed: the network broke, not the generation.
      expect(
          _state(h).generations['p1']!.status, TrackedGenerationStatus.running);

      h.repo.throwFor.remove('p1');
      await _tracker(h).debugTick();
      expect(_state(h).generations['p1']!.percent, 20);
    });

    test('emits the settled event with outcome and poll count', () async {
      final h = _harness();
      final props = <Map<String, Object?>>[];
      Analytics.testSink = (name, p) {
        if (name == 'generation_tracking_settled') props.add(p);
      };
      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');

      await _tracker(h).debugTick();

      expect(props.single['outcome'], 'succeeded');
      expect(props.single['polls'], 1);
      expect(props.single['duration_s'], isA<int>());
    });
  });

  group('monotonic percent', () {
    test('never goes backwards when a stale percent arrives late', () async {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');

      h.repo.states['p1'] = _running(percent: 60);
      await _tracker(h).debugTick();
      expect(_state(h).generations['p1']!.percent, 60);

      // A fenced, out-of-order write lands. A bar that dropped to 40% would
      // read as a bug.
      h.repo.states['p1'] = _running(percent: 40);
      await _tracker(h).debugTick();
      expect(_state(h).generations['p1']!.percent, 60);

      h.repo.states['p1'] = _running(percent: 75);
      await _tracker(h).debugTick();
      expect(_state(h).generations['p1']!.percent, 75);
    });

    test('a poll reporting no percent does not erase the one we had', () async {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');
      h.repo.states['p1'] = _running(percent: 55);
      await _tracker(h).debugTick();

      h.repo.states['p1'] = _running();
      await _tracker(h).debugTick();

      expect(_state(h).generations['p1']!.percent, 55);
    });

    test('is per project — one run cannot clamp another', () async {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).track('p2', projectName: 'Lamp');
      h.repo.states['p1'] = _running(percent: 80);
      h.repo.states['p2'] = _running(percent: 10);

      await _tracker(h).debugTick();

      expect(_state(h).generations['p1']!.percent, 80);
      expect(_state(h).generations['p2']!.percent, 10);
    });
  });

  group('suppression', () {
    test('skips a suppressed project in the poll loop WITHOUT untracking it',
        () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 30);
      h.repo.states['p2'] = _running(percent: 30);
      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).track('p2', projectName: 'Lamp');

      _tracker(h).suppress('p1');
      await _tracker(h).debugTick();

      // THE hazard this seam exists for: the build screen's own poller owns p1,
      // so the tracker must not be a second one.
      expect(h.repo.callsFor('p1'), 0);
      expect(h.repo.callsFor('p2'), 1);
      // Still tracked, still shown by the bar, still locking capture.
      expect(_state(h).generations['p1'], isNotNull);
      expect(
          _state(h).generations['p1']!.status, TrackedGenerationStatus.running);
      expect(captureLockedFor(_state(h)), isTrue);
    });

    test('unsuppress resumes asking about it', () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 30);
      _tracker(h).track('p1', projectName: 'Chair');

      _tracker(h).suppress('p1');
      await _tracker(h).debugTick();
      expect(h.repo.callsFor('p1'), 0);

      _tracker(h).unsuppress('p1');
      await _tracker(h).debugTick();
      expect(h.repo.callsFor('p1'), 1);
    });

    test('a tick that polls nothing does not burn the cap', () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 30);
      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).suppress('p1');

      // Far more ticks than the cap, all of them no-ops.
      for (var i = 0; i < 200; i++) {
        await _tracker(h).debugTick();
      }
      _tracker(h).unsuppress('p1');
      await _tracker(h).debugTick();

      // Still watched, still asking — the cap counts requests, not wake-ups.
      expect(
          _state(h).generations['p1']!.status, TrackedGenerationStatus.running);
      expect(h.repo.callsFor('p1'), 1);
    });
  });

  group('terminal entries linger, then clear', () {
    test('a succeeded entry stays visible so the bar can announce it',
        () async {
      final h = _harness();
      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');
      await _tracker(h).debugTick();

      expect(_state(h).generations['p1'], isNotNull);
    });

    test('dismiss removes it', () async {
      final h = _harness();
      h.repo.states['p1'] = _failed;
      _tracker(h).track('p1', projectName: 'Chair');
      await _tracker(h).debugTick();

      _tracker(h).dismiss('p1');
      expect(_state(h).isEmpty, isTrue);
    });
  });

  group('the capture lock predicate', () {
    test('empty does not lock', () {
      expect(captureLockedFor(const GenerationTrackerState()), isFalse);
    });

    test('a running entry locks', () {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');
      expect(captureLockedFor(_state(h)), isTrue);
      expect(h.container.read(captureLockedProvider), isTrue);
    });

    for (final (label, state) in [
      ('succeeded', _succeeded),
      ('failed', _failed),
    ]) {
      test('a $label entry does NOT lock', () async {
        final h = _harness();
        h.repo.states['p1'] = state;
        _tracker(h).track('p1', projectName: 'Chair');
        await _tracker(h).debugTick();

        expect(_state(h).generations['p1']!.isTerminal, isTrue);
        expect(captureLockedFor(_state(h)), isFalse);
        expect(h.container.read(captureLockedProvider), isFalse);
      });
    }

    test('one running entry among terminal ones still locks', () async {
      final h = _harness();
      h.repo.states['p1'] = _succeeded;
      h.repo.states['p2'] = _running(percent: 5);
      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).track('p2', projectName: 'Lamp');

      await _tracker(h).debugTick();

      expect(captureLockedFor(_state(h)), isTrue);
    });
  });

  group('persistence', () {
    test('start() restores IDS and immediately re-polls them', () async {
      final store = _FakeStore([
        TrackedGenerationRecord(
          projectId: 'p1',
          projectName: 'Chair',
          startedAt: DateTime(2026, 7, 27),
        ),
      ]);
      final h = _harness(store: store);
      h.repo.states['p1'] = _running(percent: 15);

      await _tracker(h).start();

      expect(_state(h).generations['p1'], isNotNull);
      expect(_state(h).generations['p1']!.projectName, 'Chair');
      // Asked immediately — a launch is not a resume, so nothing else would
      // have prompted this.
      expect(h.repo.callsFor('p1'), 1);
      expect(_state(h).generations['p1']!.percent, 15);
    });

    test('a restored run that finished while the app was dead settles at once',
        () async {
      final store = _FakeStore([
        TrackedGenerationRecord(
          projectId: 'p1',
          projectName: 'Chair',
          startedAt: DateTime(2026, 7, 27),
        ),
      ]);
      final h = _harness(store: store);
      h.repo.states['p1'] = _succeeded;

      await _tracker(h).start();

      expect(
        _state(h).generations['p1']!.status,
        TrackedGenerationStatus.succeeded,
      );
    });

    test('a corrupt/unreadable store yields an empty tracker and never throws',
        () async {
      final store = _FakeStore()..readThrows = true;
      final h = _harness(store: store);

      await _tracker(h).start();

      expect(_state(h).isEmpty, isTrue);
      expect(captureLockedFor(_state(h)), isFalse);
    });

    test(
        'only RUNNING entries are written — a finished one is not re-announced',
        () async {
      final h = _harness();
      await _tracker(h).start();
      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');
      expect(h.store.saved.map((r) => r.projectId), ['p1']);

      await _tracker(h).debugTick();

      expect(h.store.saved, isEmpty);
    });

    test('nothing is written before start() — construction touches no disk',
        () {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');
      expect(h.store.saveCount, 0);
    });
  });

  group('logout', () {
    test('clears everything, so one user never sees another\'s work', () async {
      final h = _harness();
      await _tracker(h).start();
      _tracker(h).track('p1', projectName: 'Chair');
      expect(_state(h).isNotEmpty, isTrue);

      h.auth.emit(const AuthUnauthenticated());
      await Future<void>.delayed(Duration.zero);

      expect(_state(h).isEmpty, isTrue);
      expect(captureLockedFor(_state(h)), isFalse);
      expect(h.store.saved, isEmpty);
    });
  });

  group('lifecycle', () {
    /// Drives the full transition chain — AppLifecycleListener derives
    /// onPause/onResume from adjacent states, so the intermediate ones matter.
    Future<void> background() async {
      final binding = TestWidgetsFlutterBinding.instance;
      for (final s in [
        AppLifecycleState.inactive,
        AppLifecycleState.hidden,
        AppLifecycleState.paused,
      ]) {
        binding.handleAppLifecycleStateChanged(s);
      }
      await Future<void>.delayed(Duration.zero);
    }

    Future<void> foreground() async {
      final binding = TestWidgetsFlutterBinding.instance;
      for (final s in [
        AppLifecycleState.hidden,
        AppLifecycleState.inactive,
        AppLifecycleState.resumed,
      ]) {
        binding.handleAppLifecycleStateChanged(s);
      }
      await Future<void>.delayed(Duration.zero);
    }

    tearDown(() {
      TestWidgetsFlutterBinding.instance
          .handleAppLifecycleStateChanged(AppLifecycleState.resumed);
    });

    test('a backgrounded app disarms the cadence and does not poll', () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 5);
      _tracker(h).track('p1', projectName: 'Chair');
      expect(_tracker(h).isPolling, isTrue);

      await background();

      expect(_tracker(h).isPolling, isFalse);
      expect(h.repo.totalCalls, 0);
    });

    test('resuming polls IMMEDIATELY and restarts the cadence', () async {
      final h = _harness();
      h.repo.states['p1'] = _running(percent: 5);
      _tracker(h).track('p1', projectName: 'Chair');
      await background();
      expect(h.repo.totalCalls, 0);

      await foreground();

      // Not after one interval — right away, because minutes may have passed.
      expect(h.repo.callsFor('p1'), 1);
      expect(_tracker(h).isPolling, isTrue);
    });
  });

  group('cadence hygiene', () {
    test('no timer is armed when nothing is running', () async {
      final h = _harness();
      expect(_tracker(h).isPolling, isFalse);

      h.repo.states['p1'] = _succeeded;
      _tracker(h).track('p1', projectName: 'Chair');
      await _tracker(h).debugTick();

      // Settled → nothing left to ask about → no wake-ups at all.
      expect(_tracker(h).isPolling, isFalse);
    });

    test('N tracked projects share ONE timer', () {
      final h = _harness();
      _tracker(h).track('p1', projectName: 'Chair');
      _tracker(h).track('p2', projectName: 'Lamp');
      _tracker(h).track('p3', projectName: 'Vase');

      expect(_state(h).runningCount, 3);
      expect(_tracker(h).isPolling, isTrue);
    });
  });
}
