// test/projects/generation_status_bar_test.dart
//
// The app-wide status bar: what it says in each state, that it stays invisible
// (and layout-neutral) when nothing is being tracked, and that its terminal
// states are actionable.
//
// The bar is driven by the REAL tracker so the copy is proven against real
// state transitions, with the Hive gateway faked — see the tracker test's note
// on why persistence is exercised in a plain `test()` instead.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:recapture/application/auth/auth_notifier.dart';
import 'package:recapture/application/projects/generation_tracker_notifier.dart';
import 'package:recapture/data/local/generation_tracker_box.dart';
import 'package:recapture/data/local/projects_cache_box.dart';
import 'package:recapture/data/local/storage_providers.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/auth_state.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/presentation/widgets/generation_status_bar.dart';

import 'repo_fake_defaults.dart';

class _FakeRepo with FakeProjectModelDefaults implements ProjectsRepository {
  final Map<String, OwnerModelState> states = {};

  @override
  Future<OwnerModelState> fetchModelState(String id) async =>
      states[id] ?? const OwnerModelState();

  @override
  Future<List<Project>> list() async => const [];

  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> rename(String id, String newName) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> delete(String id, {String? confirmName}) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> retry(String id) async =>
      throw UnimplementedError('not used here');
}

class _FakeStore implements GenerationTrackerStore {
  @override
  Future<List<TrackedGenerationRecord>> read() async => const [];
  @override
  Future<void> save(List<TrackedGenerationRecord> records) async {}
  @override
  Future<void> clear() async {}
}

class _FakeProjectsCacheBox implements ProjectsCacheBox {
  @override
  Future<CachedProjects?> read() async => null;
  @override
  Future<void> save(List<Project> projects) async {}
  @override
  Future<void> clear() async {}
}

class _FakeAuthNotifier extends AuthNotifier {
  @override
  AuthState build() => const AuthRestoring();
}

OwnerModelState _running({int? percent}) => OwnerModelState(
      generation: OwnerGenerationView(
        id: 'gen-1',
        status: ModelStatus.processing,
        isAutoGenerated: true,
        progressPercent: percent,
      ),
    );

OwnerModelState get _failedState => const OwnerModelState(
      generation: OwnerGenerationView(
        id: 'gen-1',
        status: ModelStatus.failed,
        isAutoGenerated: true,
      ),
    );

OwnerModelState get _succeededState => OwnerModelState(
      model: ProjectModelView(
        id: 'model-1',
        source: ModelSource.meshy,
        status: ModelStatus.succeeded,
        glbUrl: 'https://cdn.example.com/model.glb',
        isAutoGenerated: true,
      ),
    );

const _childKey = Key('bar_test_child');

typedef _Harness = ({
  ProviderContainer container,
  _FakeRepo repo,
  GenerationTrackerNotifier tracker,
});

/// Pumps the bar and runs [body], then disposes the container.
///
/// The dispose MUST happen inside the test body, not via `addTearDown`:
/// `testWidgets` verifies that no timers are pending at the end of the BODY,
/// before tear-downs run, and the tracker is app-scoped and non-autoDisposed —
/// so any test leaving a running entry would otherwise fail with "A Timer is
/// still pending". Disposing here cancels the cadence and linger timers.
Future<void> _withBar(
  WidgetTester tester,
  Future<void> Function(_Harness h) body, {
  void Function(GenerationBannerModel banner)? onOpen,
  Map<String, OwnerModelState> states = const {},
}) async {
  final repo = _FakeRepo()..states.addAll(states);
  final container = ProviderContainer(overrides: [
    projectsRepositoryProvider.overrideWithValue(repo),
    generationTrackerStoreProvider.overrideWithValue(_FakeStore()),
    projectsCacheBoxProvider.overrideWithValue(_FakeProjectsCacheBox()),
    authProvider.overrideWith(_FakeAuthNotifier.new),
  ]);
  try {
    await tester.pumpWidget(
      UncontrolledProviderScope(
        container: container,
        child: MaterialApp(
          home: GenerationStatusBar(
            onOpen: onOpen,
            child: const Scaffold(body: SizedBox.expand(key: _childKey)),
          ),
        ),
      ),
    );
    await tester.pump();
    await body((
      container: container,
      repo: repo,
      tracker: container.read(generationTrackerProvider.notifier),
    ));
  } finally {
    container.dispose();
  }
}

String _title(WidgetTester tester) => tester
    .widget<Text>(find.byKey(const Key('generation_status_bar_title')))
    .data!;

void main() {
  group('generationBannerFor (pure)', () {
    test('empty tracker → hidden', () {
      final banner = generationBannerFor(const GenerationTrackerState());
      expect(banner.kind, GenerationBannerKind.hidden);
      expect(banner.isVisible, isFalse);
    });

    test('a running run with no reported percent shows no number', () {
      final banner = generationBannerFor(
        GenerationTrackerState(generations: {
          'p1': TrackedGeneration(
            projectId: 'p1',
            projectName: 'Chair',
            startedAt: DateTime(2026),
          ),
        }),
      );
      expect(banner.title, 'Creating your 3D model');
      expect(banner.percent, isNull);
    });

    test('several runs never average their percents into a fake number', () {
      final banner = generationBannerFor(
        GenerationTrackerState(generations: {
          'p1': TrackedGeneration(
            projectId: 'p1',
            projectName: 'Chair',
            startedAt: DateTime(2026),
            percent: 90,
          ),
          'p2': TrackedGeneration(
            projectId: 'p2',
            projectName: 'Lamp',
            startedAt: DateTime(2026),
            percent: 10,
          ),
        }),
      );
      expect(banner.title, 'Creating 2 3D models');
      expect(banner.percent, isNull);
      // No single project → the tap goes to the Hub, not one build screen.
      expect(banner.projectId, isNull);
    });

    test('running outranks a lingering success', () {
      final banner = generationBannerFor(
        GenerationTrackerState(generations: {
          'p1': TrackedGeneration(
            projectId: 'p1',
            projectName: 'Chair',
            startedAt: DateTime(2026),
            status: TrackedGenerationStatus.succeeded,
          ),
          'p2': TrackedGeneration(
            projectId: 'p2',
            projectName: 'Lamp',
            startedAt: DateTime(2026),
          ),
        }),
      );
      expect(banner.kind, GenerationBannerKind.running);
    });

    // Success is ranked ABOVE failure so a self-clearing success is never
    // hidden behind a failure that never clears.
    test('a success is not buried under a failure', () {
      final banner = generationBannerFor(
        GenerationTrackerState(generations: {
          'p1': TrackedGeneration(
            projectId: 'p1',
            projectName: 'Chair',
            startedAt: DateTime(2026),
            status: TrackedGenerationStatus.failed,
          ),
          'p2': TrackedGeneration(
            projectId: 'p2',
            projectName: 'Lamp',
            startedAt: DateTime(2026),
            status: TrackedGenerationStatus.succeeded,
          ),
        }),
      );
      expect(banner.kind, GenerationBannerKind.succeeded);
    });

    test('gave-up says we stopped checking, not that it failed', () {
      final banner = generationBannerFor(
        GenerationTrackerState(generations: {
          'p1': TrackedGeneration(
            projectId: 'p1',
            projectName: 'Chair',
            startedAt: DateTime(2026),
            status: TrackedGenerationStatus.givenUp,
          ),
        }),
      );
      expect(banner.kind, GenerationBannerKind.failed);
      expect(banner.title, "We've stopped checking on your 3D model");
      expect(banner.isDismissible, isTrue);
    });
  });

  group('GenerationStatusBar', () {
    testWidgets('hidden when nothing is tracked — and layout-neutral',
        (tester) async {
      await _withBar(tester, (h) async {
        expect(
          find.byKey(const Key('generation_status_bar_title')),
          findsNothing,
        );
        // The child is returned untouched, so every existing screen and test
        // sees exactly the layout it saw before this feature existed.
        expect(find.byType(Column), findsNothing);
        expect(
          tester.getSize(find.byKey(_childKey)),
          tester.getSize(find.byType(MaterialApp)),
        );
      });
    });

    testWidgets('one running generation names it and shows the percent',
        (tester) async {
      await _withBar(
        tester,
        states: {'p1': _running(percent: 42)},
        (h) async {
          h.tracker.track('p1', projectName: 'Chair');
          await h.tracker.debugTick();
          await tester.pump();

          expect(_title(tester), 'Creating your 3D model · 42%');
          final bar = tester.widget<LinearProgressIndicator>(
            find.byKey(const Key('generation_status_bar_progress')),
          );
          expect(bar.value, closeTo(0.42, 0.001));
        },
      );
    });

    testWidgets('an unreported percent renders indeterminate, never 0%',
        (tester) async {
      await _withBar(tester, (h) async {
        h.tracker.track('p1', projectName: 'Chair');
        await tester.pump();

        expect(_title(tester), 'Creating your 3D model');
        expect(find.textContaining('0%'), findsNothing);
        final bar = tester.widget<LinearProgressIndicator>(
          find.byKey(const Key('generation_status_bar_progress')),
        );
        expect(bar.value, isNull);
      });
    });

    testWidgets('two running generations aggregate', (tester) async {
      await _withBar(tester, (h) async {
        h.tracker.track('p1', projectName: 'Chair');
        h.tracker.track('p2', projectName: 'Lamp');
        await tester.pump();

        expect(_title(tester), 'Creating 2 3D models');
      });
    });

    testWidgets('the bar pushes content down rather than covering it',
        (tester) async {
      await _withBar(tester, (h) async {
        final fullHeight = tester.getSize(find.byKey(_childKey)).height;

        h.tracker.track('p1', projectName: 'Chair');
        await tester.pump();

        expect(
          tester.getSize(find.byKey(_childKey)).height,
          lessThan(fullHeight),
        );
        expect(tester.getTopLeft(find.byKey(_childKey)).dy, greaterThan(0));
      });
    });

    testWidgets('a succeeded generation is announced and is tappable',
        (tester) async {
      final opened = <GenerationBannerModel>[];
      await _withBar(
        tester,
        states: {'p1': _succeededState},
        onOpen: opened.add,
        (h) async {
          h.tracker.track('p1', projectName: 'Chair');
          await h.tracker.debugTick();
          await tester.pump();

          expect(_title(tester), 'Your 3D model is ready');

          await tester
              .tap(find.byKey(const Key('generation_status_bar_title')));
          await tester.pump();

          expect(opened.single.projectId, 'p1');
          expect(opened.single.projectName, 'Chair');
        },
      );
    });

    testWidgets('a failed generation is owner-safe and dismissible',
        (tester) async {
      await _withBar(
        tester,
        states: {'p1': _failedState},
        (h) async {
          h.tracker.track('p1', projectName: 'Chair');
          await h.tracker.debugTick();
          await tester.pump();

          expect(_title(tester), "We couldn't create your 3D model");
          // The rule ModelBuildingScreen already follows: no code, no URL, no
          // vendor name.
          expect(find.textContaining('Meshy'), findsNothing);
          expect(find.textContaining('gen-1'), findsNothing);

          await tester
              .tap(find.byKey(const Key('generation_status_bar_dismiss')));
          await tester.pump();

          expect(
            find.byKey(const Key('generation_status_bar_title')),
            findsNothing,
          );
          expect(h.container.read(generationTrackerProvider).isEmpty, isTrue);
        },
      );
    });

    testWidgets('a running generation offers no dismiss', (tester) async {
      await _withBar(tester, (h) async {
        h.tracker.track('p1', projectName: 'Chair');
        await tester.pump();

        expect(
          find.byKey(const Key('generation_status_bar_dismiss')),
          findsNothing,
        );
      });
    });

    testWidgets('height is stable across polls so screens do not reflow',
        (tester) async {
      await _withBar(
        tester,
        states: {'p1': _running(percent: 10)},
        (h) async {
          h.tracker.track('p1', projectName: 'Chair');
          await h.tracker.debugTick();
          await tester.pump();
          final firstTop = tester.getTopLeft(find.byKey(_childKey)).dy;

          h.repo.states['p1'] = _running(percent: 88);
          await h.tracker.debugTick();
          await tester.pump();

          expect(_title(tester), 'Creating your 3D model · 88%');
          expect(tester.getTopLeft(find.byKey(_childKey)).dy, firstTop);
        },
      );
    });
  });
}
