// test/projects/model_generation_button_test.dart
//
// The "Generate 3D model" button and the screen it opens.
//
// The load-bearing tests here are the two that protect users rather than
// features: a DECLINE must reach the user as plain, actionable copy with no
// rule id / key / URL in the widget tree, and the progress bar must never move
// backwards when a fenced, best-effort progress write arrives out of order.
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:recapture/app/theme/app_theme.dart';
import 'package:recapture/application/auth/user_role_notifier.dart';
import 'package:recapture/application/projects/model_generation_request_notifier.dart';
import 'package:recapture/data/repositories/live_projects_repository.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/generation_trace.dart';
import 'package:recapture/domain/entities/live_project.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/domain/entities/project_status.dart';
import 'package:recapture/presentation/screens/projects/live_projects_view.dart';
import 'package:recapture/presentation/screens/projects/model_building_screen.dart';
import 'package:recapture/presentation/widgets/project_card.dart';

import 'repo_fake_defaults.dart';

Project _project(ProjectStatus status) => Project(
      id: 'proj-123',
      name: 'My Project',
      status: status,
      updatedAt: DateTime(2026, 7, 1),
    );

// ── Fakes ────────────────────────────────────────────────────────────────────

class _StubLiveRepo
    with
        FakeModelGenerationDefaults,
        FakeAdminDeleteDefaults,
        FakeModelImageUploadDefaults
    implements LiveProjectsRepository {
  _StubLiveRepo({this.page, this.result, this.failure, this.gate});

  final LiveProjectsPage? page;
  final AutoGenerationRequest? result;
  final LiveProjectsException? failure;

  /// Holds the response open so two presses genuinely overlap. Deliberately a
  /// Completer and not a delay: inside `testWidgets` the clock is fake, so a
  /// `Future.delayed` that nothing pumps never completes and the test hangs.
  final Completer<void>? gate;

  /// Every autoGenerateModel call, as (projectId, force).
  final List<(String, bool)> generated = [];

  @override
  Future<LiveProjectsPage> list({int limit = 20, String? cursor}) async =>
      page ?? const LiveProjectsPage(items: [], nextCursor: null);

  @override
  Future<AutoGenerationRequest> autoGenerateModel(
    String projectId, {
    bool force = false,
  }) async {
    generated.add((projectId, force));
    if (gate != null) await gate!.future;
    if (failure != null) throw failure!;
    return result ??
        const AutoGenerationRequest(outcome: AutoGenerationOutcome.enqueued);
  }

  @override
  Future<Map<String, dynamic>> export(String projectId) async =>
      throw UnimplementedError();

  @override
  Future<PreviewDeleteResult> deletePhotos(
          String projectId, List<String> keys) async =>
      throw UnimplementedError();
}

/// Owner model state that yields a scripted sequence, one entry per poll.
class _StubProjectsRepo with FakeProjectModelDefaults implements ProjectsRepository {
  _StubProjectsRepo(this._states);

  final List<OwnerModelState> _states;
  int _reads = 0;

  @override
  Future<OwnerModelState> fetchModelState(String id) async {
    final state = _states[_reads.clamp(0, _states.length - 1)];
    _reads++;
    return state;
  }

  @override
  Future<List<Project>> list() async => const [];
  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError();
  @override
  Future<void> rename(String id, String newName) async {}
  @override
  Future<void> delete(String id, {String? confirmName}) async {}
  @override
  Future<void> retry(String id) async {}
}

OwnerModelState _generating(int? percent) => OwnerModelState(
      generation: OwnerGenerationView(
        id: 'gen-1',
        status: ModelStatus.processing,
        isAutoGenerated: false,
        progressPercent: percent,
      ),
    );

Widget _screen({required ProviderContainer container}) {
  return UncontrolledProviderScope(
    container: container,
    child: MaterialApp(
      theme: AppTheme.dark,
      home: const ModelBuildingScreen(
        projectId: 'proj-123',
        projectName: 'My Project',
      ),
    ),
  );
}

void main() {
  // ── The button's visibility contract ──────────────────────────────────────

  group('ProjectCard onGenerate', () {
    testWidgets('null → no button, card unchanged for regular users',
        (tester) async {
      await tester.pumpWidget(MaterialApp(
        theme: AppTheme.dark,
        home: Scaffold(
          body: ProjectCard(
            project: _project(ProjectStatus.completed),
            onResume: (_) {},
            onView: (_) {},
            onRetry: (_) {},
            onMore: (_) {},
          ),
        ),
      ));
      expect(find.text('Generate 3D model'), findsNothing);
    });

    testWidgets('non-null → button shows and calls back with the project',
        (tester) async {
      Project? tapped;
      await tester.pumpWidget(MaterialApp(
        theme: AppTheme.dark,
        home: Scaffold(
          body: ProjectCard(
            project: _project(ProjectStatus.completed),
            onResume: (_) {},
            onView: (_) {},
            onRetry: (_) {},
            onMore: (_) {},
            onGenerate: (p) => tapped = p,
          ),
        ),
      ));
      expect(find.text('Generate 3D model'), findsOneWidget);
      await tester.tap(find.text('Generate 3D model'));
      expect(tapped?.id, 'proj-123');
    });
  });

  group('Live tab card', () {
    Future<void> pumpLive(WidgetTester tester, ProjectStatus status) async {
      final repo = _StubLiveRepo(
        page: LiveProjectsPage(
          items: [
            LiveProject(
              id: 'proj-123',
              name: 'Live Project',
              status: status,
              updatedAt: DateTime(2026, 7, 1),
              ownerId: 'owner-abcdef',
              totalPhotos: 48,
            ),
          ],
          nextCursor: null,
        ),
      );
      await tester.pumpWidget(ProviderScope(
        overrides: [
          liveProjectsRepositoryProvider.overrideWithValue(repo),
          // Without this the real role chain opens Hive.
          isAdminProvider.overrideWithValue(false),
        ],
        child: MaterialApp(
          theme: AppTheme.dark,
          home: const Scaffold(body: LiveProjectsView()),
        ),
      ));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));
    }

    testWidgets('shows Generate for a project with a finalized capture',
        (tester) async {
      await pumpLive(tester, ProjectStatus.completed);
      expect(find.text('Generate 3D model'), findsOneWidget);
    });

    testWidgets('hides Generate when there is no finalized capture',
        (tester) async {
      // A button that could only ever be refused is worse than no button.
      await pumpLive(tester, ProjectStatus.draft);
      expect(find.text('Generate 3D model'), findsNothing);
    });
  });

  // ── The request itself ────────────────────────────────────────────────────

  group('ModelGenerationRequestNotifier', () {
    test('a second press while one is in flight does not pay twice', () async {
      final gate = Completer<void>();
      final repo = _StubLiveRepo(gate: gate);
      final container = ProviderContainer(overrides: [
        liveProjectsRepositoryProvider.overrideWithValue(repo),
      ]);
      addTearDown(container.dispose);

      final notifier =
          container.read(modelGenerationRequestProvider('proj-123').notifier);
      final first = notifier.request();
      final second = notifier.request();
      gate.complete();
      await Future.wait([first, second]);

      // The money assertion: one press, one charge.
      expect(repo.generated, hasLength(1));
    });

    test('a ceiling refusal becomes state, not an exception', () async {
      final repo = _StubLiveRepo(
        failure: const LiveProjectsException(
          LiveProjectsFailure.dailyLimitReached,
        ),
      );
      final container = ProviderContainer(overrides: [
        liveProjectsRepositoryProvider.overrideWithValue(repo),
      ]);
      addTearDown(container.dispose);

      final state = await container
          .read(modelGenerationRequestProvider('proj-123').notifier)
          .request();

      expect(state.failure, LiveProjectsFailure.dailyLimitReached);
      expect(state.hasResult, isFalse);
    });
  });

  // ── The screen ────────────────────────────────────────────────────────────

  group('ModelBuildingScreen', () {
    ProviderContainer containerWith({
      required _StubLiveRepo live,
      required List<OwnerModelState> ownerStates,
      bool isStaff = true,
    }) {
      return ProviderContainer(overrides: [
        liveProjectsRepositoryProvider.overrideWithValue(live),
        projectsRepositoryProvider
            .overrideWithValue(_StubProjectsRepo(ownerStates)),
        isStaffProvider.overrideWithValue(isStaff),
      ]);
    }

    testWidgets('a decline shows actionable copy and leaks no internals',
        (tester) async {
      final live = _StubLiveRepo(
        result: const AutoGenerationRequest(
          outcome: AutoGenerationOutcome.declined,
          declineReason: GenerationDeclineReason.insufficientSpread,
          steps: [
            GenerationStep(
              name: GenerationStepName.selectPhotos,
              status: GenerationStepStatus.failed,
              rawName: 'SELECT_PHOTOS',
              detail: 'INSUFFICIENT_SPREAD: quadrants=[6,0,0,0]',
            ),
          ],
          trace: GenerationSelectionTrace(
            poolSize: 6,
            quadrantHistogram: [6, 0, 0, 0],
            chosen: [ChosenPhoto(key: 'images/EYE/eye_0001.jpg')],
          ),
        ),
      );
      final container =
          containerWith(live: live, ownerStates: [const OwnerModelState()],
              // Not staff: the dev trace must be entirely absent, which is
              // also what makes the leak assertion below meaningful.
              isStaff: false);
      addTearDown(container.dispose);

      await container
          .read(modelGenerationRequestProvider('proj-123').notifier)
          .request();
      await tester.pumpWidget(_screen(container: container));
      await tester.pump();

      expect(
        find.textContaining('Walk all the way around it'),
        findsOneWidget,
      );
      // Nothing internal reaches the tree: not the rule id, not a key, not the
      // step vocabulary.
      final texts = tester
          .widgetList<Text>(find.byType(Text))
          .map((t) => t.data ?? '')
          .join('\n');
      expect(texts, isNot(contains('INSUFFICIENT_SPREAD')));
      expect(texts, isNot(contains('images/EYE')));
      expect(texts, isNot(contains('SELECT_PHOTOS')));
      expect(find.text('Selection trace (dev)'), findsNothing);
    });

    testWidgets('the dev trace appears for staff and names the counters',
        (tester) async {
      final live = _StubLiveRepo(
        result: const AutoGenerationRequest(
          outcome: AutoGenerationOutcome.enqueued,
          steps: [
            GenerationStep(
              name: GenerationStepName.selectPhotos,
              status: GenerationStepStatus.ok,
              rawName: 'SELECT_PHOTOS',
              detail: '4 photos from 4 of 4 yaw quadrants',
              durationMs: 3,
            ),
          ],
          trace: GenerationSelectionTrace(
            poolSize: 16,
            photosInManifest: 36,
            droppedNoBlurScore: 0,
            quadrantHistogram: [4, 4, 4, 4],
            chosen: [ChosenPhoto(key: 'images/EYE/eye_0001.jpg', blurScore: 85)],
          ),
        ),
      );
      final container = containerWith(
        live: live,
        ownerStates: [_generating(10)],
      );
      addTearDown(container.dispose);

      await container
          .read(modelGenerationRequestProvider('proj-123').notifier)
          .request();
      await tester.pumpWidget(_screen(container: container));
      await tester.pump();
      await tester.pump();

      expect(find.text('Selection trace (dev)'), findsOneWidget);
      // And the owner-facing timeline is there regardless of the dev block.
      expect(find.text('Choosing your best photos'), findsOneWidget);

      // Stop the poll timer before the test ends — a live timer trips the
      // binding's "still pending after disposal" invariant.
      container.dispose();
    });

    // REGRESSION: progress writes are best-effort and fenced, so a percent can
    // arrive stale. A bar that jumps backwards reads as a broken app.
    testWidgets('progress never moves backwards', (tester) async {
      final live = _StubLiveRepo();
      final container = containerWith(
        live: live,
        ownerStates: [_generating(60), _generating(30), _generating(30)],
      );
      addTearDown(container.dispose);

      await container
          .read(modelGenerationRequestProvider('proj-123').notifier)
          .request();
      await tester.pumpWidget(_screen(container: container));
      await tester.pump();
      await tester.pump();
      expect(find.text('60%'), findsOneWidget);

      // The next poll returns a SMALLER number.
      await tester.pump(const Duration(seconds: 4));
      await tester.pump();
      expect(find.text('60%'), findsOneWidget);
      expect(find.text('30%'), findsNothing);

      // Stop the notifier's timer before the test ends.
      container.dispose();
    });
  });
}
