// test/projects/owner_models_screen_test.dart
//
// The OWNER's "all my models" list — the screen that replaces "here is your
// model" with "here are your models, pick one":
//   • every finished model is listed, in the server's newest-first order, and
//     the build the project actually opens is marked "In use";
//   • ONE generation that was optimized shows BOTH builds — two rows sharing an
//     id, pointing at different files. That is the bug this screen was missing:
//     the optimized build is a rendition of the same record, so an owner who
//     was told their model was optimized could only ever see the served one;
//   • a model whose web build is still running is INERT — opening it would
//     serve the heavy original we are about to replace;
//   • a tap carries THAT row's model, not the newest one — the entire point of
//     the screen is choosing between versions;
//   • an empty list and a failed load both say something, and the failure says
//     it in mapped copy: no code, no URL, no raw error.
//
// Hermetic: fake repository, no network. The real viewer needs a WebView
// platform, so the open is intercepted via onOpenModel.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:recapture/app/theme/app_theme.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/presentation/screens/projects/owner_models_screen.dart';
import 'repo_fake_defaults.dart';

class _FakeRepo with FakeProjectModelDefaults implements ProjectsRepository {
  _FakeRepo(this.models, {this.fails = false});

  final List<ProjectModelView> models;
  final bool fails;
  int calls = 0;

  @override
  Future<List<ProjectModelView>> fetchModels(String id) async {
    calls++;
    if (fails) throw Exception('boom: https://cdn.example/secret.glb');
    return models;
  }

  @override
  Future<List<Project>> list() async => const [];

  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> rename(String id, String newName) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> delete(String id, {String? confirmName}) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> retry(String id) async => throw UnimplementedError('not used here');
}

ProjectModelView _model({
  required String id,
  required DateTime at,
  bool isAutoGenerated = true,
  bool optimizationPending = false,
  ModelVariant variant = ModelVariant.original,
  bool isActiveVariant = true,
  int? bytes,
}) =>
    ProjectModelView(
      id: id,
      source: ModelSource.meshy,
      status: ModelStatus.succeeded,
      glbUrl: 'https://cdn/$id-${variant.name}.glb',
      createdAt: at,
      isAutoGenerated: isAutoGenerated,
      optimizationPending: optimizationPending,
      variant: variant,
      isActiveVariant: isActiveVariant,
      metrics: bytes == null
          ? null
          : ModelMetrics(
              bytes: bytes,
              triangles: 0,
              textureCount: 0,
              largestTextureBytes: 0,
            ),
    );

Widget _app(_FakeRepo repo, {void Function(ProjectModelView)? onOpen}) =>
    ProviderScope(
      overrides: [projectsRepositoryProvider.overrideWithValue(repo)],
      child: MaterialApp(
        theme: AppTheme.dark,
        home: OwnerModelsScreen(
          projectId: 'p1',
          projectName: 'My Chair',
          onOpenModel: onOpen,
        ),
      ),
    );

void main() {
  group('OwnerModelsScreen', () {
    testWidgets('lists every finished model newest-first, marking the served one',
        (tester) async {
      final repo = _FakeRepo([
        _model(id: 'm2', at: DateTime(2026, 8, 5, 11, 42)),
        _model(id: 'm1', at: DateTime(2026, 8, 4, 9, 7), isAutoGenerated: false),
      ]);
      await tester.pumpWidget(_app(repo));
      await tester.pumpAndSettle();

      // Labelled by WHEN — an index would renumber itself as new generations
      // land at the head of the list.
      expect(find.text('Aug 5, 11:42'), findsOneWidget);
      expect(find.text('Aug 4, 09:07'), findsOneWidget);

      // "Serving" belongs to the newest generation's active build ONLY. The
      // older generation's build is also `isActiveVariant` — of a generation
      // that is served nowhere — so marking it too would name two winners.
      expect(find.text('Serving · AI generated'), findsOneWidget);
      expect(find.text('Made for you'), findsOneWidget);

      final newest = tester
          .getTopLeft(find.byKey(const ValueKey('owner_model_row_m2_original')));
      final older = tester
          .getTopLeft(find.byKey(const ValueKey('owner_model_row_m1_original')));
      expect(newest.dy, lessThan(older.dy));
    });

    testWidgets(
        'one optimized generation shows BOTH builds — same id, different files',
        (tester) async {
      // The regression: a capture that was optimized is one generation with two
      // openable builds. Showing only the served one is what hid the other.
      ProjectModelView? opened;
      final repo = _FakeRepo([
        _model(
          id: 'm1',
          at: DateTime(2026, 8, 5, 11, 42),
          variant: ModelVariant.web,
          bytes: 318000,
        ),
        _model(
          id: 'm1',
          at: DateTime(2026, 8, 5, 11, 42),
          variant: ModelVariant.original,
          isActiveVariant: false,
          bytes: 7920000,
        ),
      ]);
      await tester.pumpWidget(_app(repo, onOpen: (m) => opened = m));
      await tester.pumpAndSettle();

      // Two rows for one generation, told apart by build and by weight — the
      // numbers are the only objective way to choose between them. Badged on
      // the optimized row ONLY, the same one-bit distinction the staff history
      // draws; the unbadged row is the original.
      expect(find.text('OPT'), findsOneWidget);
      expect(find.textContaining('318 KB'), findsOneWidget);
      expect(find.textContaining('7.92 MB'), findsOneWidget);
      // The served build, marked in the staff vocabulary.
      expect(find.textContaining('318 KB · Serving'), findsOneWidget);
      // Duplicated timestamps look like a bug until they're explained.
      expect(find.textContaining('two versions'), findsOneWidget);
      // The full-detail build is the one that can fail to load on a phone —
      // said before the tap, not discovered after it.
      expect(find.textContaining('May not load on every phone'), findsOneWidget);

      // The un-served build opens its OWN file, not the one being served.
      await tester
          .tap(find.byKey(const ValueKey('owner_model_row_m1_original')));
      await tester.pump();
      expect(opened?.glbUrl, 'https://cdn/m1-original.glb');
    });

    testWidgets('a tap opens THAT row\'s model, not the newest', (tester) async {
      ProjectModelView? opened;
      final repo = _FakeRepo([
        _model(id: 'm2', at: DateTime(2026, 8, 5, 11, 42)),
        _model(id: 'm1', at: DateTime(2026, 8, 4, 9, 7)),
      ]);
      await tester.pumpWidget(_app(repo, onOpen: (m) => opened = m));
      await tester.pumpAndSettle();

      // The OLDER row: comparing versions is the whole reason this screen
      // exists, so the tap must carry the row's own model.
      await tester
          .tap(find.byKey(const ValueKey('owner_model_row_m1_original')));
      await tester.pump();

      expect(opened?.id, 'm1');
      expect(opened?.glbUrl, 'https://cdn/m1-original.glb');
    });

    testWidgets('a model still being optimized is inert, and says so',
        (tester) async {
      ProjectModelView? opened;
      final repo = _FakeRepo([
        _model(
          id: 'm1',
          at: DateTime(2026, 8, 5, 11, 42),
          optimizationPending: true,
        ),
      ]);
      await tester.pumpWidget(_app(repo, onOpen: (m) => opened = m));
      // NOT pumpAndSettle: the row's spinner animates forever, so settling
      // would hang rather than fail.
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(find.textContaining('Finishing up'), findsOneWidget);
      expect(
        find.descendant(
          of: find.byKey(const ValueKey('owner_model_row_m1_original')),
          matching: find.byType(CircularProgressIndicator),
        ),
        findsOneWidget,
      );

      // Opening it now would serve the heavy original we are about to replace —
      // the "we couldn't load this model" build.
      await tester.tap(find.byKey(const ValueKey('owner_model_row_m1_original')));
      await tester.pump();
      expect(opened, isNull);
    });

    testWidgets('no models → an empty state rather than a blank screen',
        (tester) async {
      await tester.pumpWidget(_app(_FakeRepo(const [])));
      await tester.pumpAndSettle();

      expect(find.text('No models yet.'), findsOneWidget);
    });

    testWidgets('a failed load shows mapped copy only, and retries',
        (tester) async {
      final repo = _FakeRepo(const [], fails: true);
      await tester.pumpWidget(_app(repo));
      await tester.pumpAndSettle();

      expect(find.textContaining("couldn't load your models"), findsOneWidget);
      // Never the raw error: no exception text, no URL. Same rule as 9F.
      expect(find.textContaining('boom'), findsNothing);
      expect(find.textContaining('cdn.example'), findsNothing);

      final before = repo.calls;
      await tester.tap(find.text('Retry'));
      await tester.pumpAndSettle();
      expect(repo.calls, greaterThan(before));
    });
  });
}
