// test/projects/owner_models_routing_test.dart
//
// WHERE an owner's model taps land, now that a project can show more than one
// model:
//   • "Models" ALWAYS opens the list;
//   • "View" takes the shortcut only when there is nothing to choose between —
//     one openable model still opens directly, exactly as it did before this
//     screen existed;
//   • the count that decides comes from the MODELS ENDPOINT, not from the
//     card's `modelCount`. That is the regression these tests pin: one
//     generation that was optimized offers TWO openable builds while
//     `modelCount` — one per generation — says 1, so routing on the card's
//     count dropped the owner into whichever build happened to be served and
//     hid the other one entirely.
//
// Hermetic: fake notifier + fake repository, no network.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:recapture/application/auth/profile_provider.dart';
import 'package:recapture/application/auth/user_role_notifier.dart';
import 'package:recapture/application/projects/projects_notifier.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/domain/entities/project_status.dart';
import 'package:recapture/presentation/screens/projects/model_building_screen.dart';
import 'package:recapture/presentation/screens/projects/owner_models_screen.dart';
import 'package:recapture/presentation/screens/projects/projects_screen.dart';

/// Owner list with a caller-chosen model count, COMPLETED so the card offers
/// both "View" and "Models".
class _FakeProjectsNotifier extends ProjectsNotifier {
  _FakeProjectsNotifier(this.modelCount);
  final int modelCount;

  @override
  Future<List<Project>> build() async => [
        Project(
          id: 'p1',
          name: 'My vase',
          status: ProjectStatus.completed,
          updatedAt: DateTime(2026, 8, 5),
          totalPhotos: 36,
          modelCount: modelCount,
        ),
      ];
}

/// Counts which owner endpoint each tap reached.
class _RecordingRepo implements ProjectsRepository {
  _RecordingRepo(this.models, {this.settled = true});

  final List<ProjectModelView> models;

  /// Whether the project has a finished model to open. False stands in for "a
  /// generation is still running", whose destination is the build screen — the
  /// one branch of [_onView] a widget test can follow, since the viewer needs a
  /// WebView platform that does not exist here.
  final bool settled;

  int modelStateCalls = 0;
  int modelsCalls = 0;

  @override
  Future<List<ProjectModelView>> fetchModels(String id) async {
    modelsCalls++;
    return models;
  }

  @override
  Future<OwnerModelState> fetchModelState(String id) async {
    modelStateCalls++;
    if (settled) return OwnerModelState(model: models.first);
    return const OwnerModelState(
      generation: OwnerGenerationView(
        id: 'g1',
        status: ModelStatus.processing,
        isAutoGenerated: true,
      ),
    );
  }

  @override
  Future<ProjectModelView?> fetchModel(String id) async => null;

  @override
  Future<OwnerGenerationRequestResult> requestModelGeneration(
    String id, {
    bool regenerate = false,
  }) async =>
      throw UnimplementedError('not used here');

  /// Throws on purpose: the screen's silent background refresh (and the one on
  /// returning from a pushed screen) would otherwise succeed and write the Hive
  /// cache, which has no path in a widget test. A failed silent refresh is
  /// swallowed by design and leaves the fake list on screen.
  @override
  Future<List<Project>> list() async => throw Exception('no background refresh');

  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> rename(String id, String newName) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> delete(String id, {String? confirmName}) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> retry(String id) async => throw UnimplementedError('not used here');
}

Widget _app(_RecordingRepo repo, {required int modelCount}) => ProviderScope(
      overrides: [
        projectsProvider.overrideWith(() => _FakeProjectsNotifier(modelCount)),
        projectsRepositoryProvider.overrideWithValue(repo),
        // The owner, not staff: staff "Models" goes to the admin history route.
        isStaffProvider.overrideWithValue(false),
        isAdminProvider.overrideWithValue(false),
        avatarBytesProvider.overrideWith((ref) async => null),
      ],
      child: const MaterialApp(home: ProjectsScreen()),
    );

/// Bounded pump: pushed screens keep spinners/poll timers alive, so
/// pumpAndSettle would hang rather than fail.
Future<void> _pumpFrames(WidgetTester tester) async {
  for (var i = 0; i < 5; i++) {
    await tester.pump(const Duration(milliseconds: 100));
  }
}

ProjectModelView _rendition(ModelVariant variant, {bool isActive = false}) =>
    ProjectModelView(
      id: 'm1',
      source: ModelSource.meshy,
      status: ModelStatus.succeeded,
      glbUrl: 'https://cdn/m1-${variant.name}.glb',
      createdAt: DateTime(2026, 8, 5, 11, 42),
      variant: variant,
      isActiveVariant: isActive,
    );

void main() {
  testWidgets(
      'ONE optimized generation still routes View to the list, though the card '
      'counts it as a single model', (tester) async {
    // Exactly what the server reports for a capture that was then optimized:
    // one generation record, two openable builds — and `modelCount` 1.
    final repo = _RecordingRepo([
      _rendition(ModelVariant.web, isActive: true),
      _rendition(ModelVariant.original),
    ]);
    await tester.pumpWidget(_app(repo, modelCount: 1));
    await _pumpFrames(tester);

    await tester.tap(find.text('View'));
    await _pumpFrames(tester);

    expect(find.byType(OwnerModelsScreen), findsOneWidget);
    expect(repo.modelsCalls, greaterThanOrEqualTo(1));
  });

  testWidgets('one openable build → View keeps the pre-existing path',
      (tester) async {
    final repo = _RecordingRepo(
      [_rendition(ModelVariant.original, isActive: true)],
      settled: false,
    );
    await tester.pumpWidget(_app(repo, modelCount: 1));
    await _pumpFrames(tester);

    await tester.tap(find.text('View'));
    await _pumpFrames(tester);

    // The list was consulted and found nothing to choose between, so the tap
    // resolves on the model state exactly as it did before this screen existed.
    expect(repo.modelsCalls, 1);
    expect(find.byType(OwnerModelsScreen), findsNothing);
    // At least the tap's own resolve — the build screen it lands on watches the
    // same endpoint, so it adds its own reads on top.
    expect(repo.modelStateCalls, greaterThanOrEqualTo(1));
    // The pre-existing destination for "a generation is in flight".
    expect(find.byType(ModelBuildingScreen), findsOneWidget);
  });

  testWidgets('Models always opens the list, even for a single model',
      (tester) async {
    final repo =
        _RecordingRepo([_rendition(ModelVariant.original, isActive: true)]);
    await tester.pumpWidget(_app(repo, modelCount: 1));
    await _pumpFrames(tester);

    await tester.tap(find.text('Models'));
    await _pumpFrames(tester);

    expect(find.byType(OwnerModelsScreen), findsOneWidget);
    expect(repo.modelsCalls, 1);
    // Straight to the list: nothing to resolve first.
    expect(repo.modelStateCalls, 0);
  });
}
