// test/projects/owner_model_state_test.dart
//
// The OWNER-facing auto-generation surface: parsing `GET /projects/:id`'s
// `generation` block, and the three states ModelBuildingScreen must render.
//
// The load-bearing case is "a finished model AND a newer generation at once" —
// the situation automatic regeneration creates, where showing the wait instead
// of the model would take away something the user already has.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:recapture/data/repositories/projects_repository.dart';
import 'package:recapture/domain/entities/create_project_options.dart';
import 'package:recapture/domain/entities/project.dart';
import 'package:recapture/domain/entities/project_model.dart';
import 'package:recapture/presentation/screens/projects/model_building_screen.dart';

import 'repo_fake_defaults.dart';

/// A repository whose model state is whatever the test says it is.
class _FakeRepo with FakeProjectModelDefaults implements ProjectsRepository {
  _FakeRepo(this._state);

  final OwnerModelState _state;
  int calls = 0;

  @override
  Future<OwnerModelState> fetchModelState(String id) async {
    calls++;
    return _state;
  }

  @override
  Future<List<Project>> list() async => const [];

  @override
  Future<Project> create({
    required String name,
    required ObjectSize size,
    required CaptureMode mode,
  }) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> rename(String id, String newName) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> delete(String id, {String? confirmName}) async =>
      throw UnimplementedError('not used here');

  @override
  Future<void> retry(String id) async => throw UnimplementedError('not used here');
}

ProjectModelView _finishedModel({bool isAutoGenerated = true}) => ProjectModelView(
      id: 'model-1',
      source: ModelSource.meshy,
      status: ModelStatus.succeeded,
      glbUrl: 'https://cdn.example.com/model.glb',
      isAutoGenerated: isAutoGenerated,
    );

Future<void> _pump(WidgetTester tester, OwnerModelState state) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [projectsRepositoryProvider.overrideWithValue(_FakeRepo(state))],
      child: const MaterialApp(
        home: ModelBuildingScreen(projectId: 'p1', projectName: 'Chair'),
      ),
    ),
  );
  await tester.pump(); // resolve the initial fetch
}

void main() {
  group('OwnerGenerationView.tryParse', () {
    test('parses a pending generation', () {
      final view = OwnerGenerationView.tryParse({
        'id': 'gen-1',
        'status': 'PROCESSING',
        'isAutoGenerated': true,
        'progressPercent': 42,
      });

      expect(view, isNotNull);
      expect(view!.id, 'gen-1');
      expect(view.isPending, isTrue);
      expect(view.isAutoGenerated, isTrue);
      expect(view.progressPercent, 42);
    });

    test('clamps a nonsensical percent instead of overflowing a progress bar', () {
      expect(
        OwnerGenerationView.tryParse(
          {'id': 'g', 'status': 'PROCESSING', 'progressPercent': 900},
        )!.progressPercent,
        100,
      );
    });

    test('treats a missing percent as unknown, not zero', () {
      // Zero would render an empty bar and read as "stuck at 0%"; null renders
      // indeterminate, which is the truth.
      expect(
        OwnerGenerationView.tryParse({'id': 'g', 'status': 'QUEUED'})!.progressPercent,
        isNull,
      );
    });

    test('returns null for absent or malformed payloads', () {
      for (final bad in [null, 'nope', 42, <String, dynamic>{}, {'id': ''}]) {
        expect(OwnerGenerationView.tryParse(bad), isNull);
      }
    });

    test('an unknown status is terminal so polling cannot spin forever', () {
      final view = OwnerGenerationView.tryParse({'id': 'g', 'status': 'WAT'});
      expect(view!.isPending, isFalse);
    });
  });

  group('OwnerModelState', () {
    test('isGenerating only while the run is pending', () {
      expect(
        const OwnerModelState(
          generation: OwnerGenerationView(
            id: 'g',
            status: ModelStatus.processing,
            isAutoGenerated: true,
          ),
        ).isGenerating,
        isTrue,
      );
      expect(
        const OwnerModelState(
          generation: OwnerGenerationView(
            id: 'g',
            status: ModelStatus.failed,
            isAutoGenerated: true,
          ),
        ).isGenerating,
        isFalse,
      );
    });
  });

  group('ModelBuildingScreen', () {
    testWidgets('waiting state explains the wait and says leaving is safe',
        (tester) async {
      await _pump(
        tester,
        const OwnerModelState(
          generation: OwnerGenerationView(
            id: 'g',
            status: ModelStatus.processing,
            isAutoGenerated: true,
            progressPercent: 30,
          ),
        ),
      );

      expect(find.text('Creating your 3D model'), findsOneWidget);
      expect(find.text('This usually takes a few minutes.'), findsOneWidget);
      expect(find.text('30%'), findsOneWidget);
      expect(find.textContaining('You can leave this screen'), findsOneWidget);
    });

    testWidgets('unknown progress renders an indeterminate bar, not 0%',
        (tester) async {
      await _pump(
        tester,
        const OwnerModelState(
          generation: OwnerGenerationView(
            id: 'g',
            status: ModelStatus.queued,
            isAutoGenerated: true,
          ),
        ),
      );

      expect(find.text('0%'), findsNothing);
      final bar = tester.widget<LinearProgressIndicator>(
        find.byType(LinearProgressIndicator),
      );
      expect(bar.value, isNull);
    });

    testWidgets('ready state badges an auto-generated model as preview quality',
        (tester) async {
      await _pump(tester, OwnerModelState(model: _finishedModel()));

      expect(find.text('Your 3D model is ready'), findsOneWidget);
      expect(find.text(kAutoGeneratedBadgeLabel), findsOneWidget);
      expect(find.text('View 3D model'), findsOneWidget);
    });

    testWidgets('a staff-requested model is not badged as auto-generated',
        (tester) async {
      await _pump(
        tester,
        OwnerModelState(model: _finishedModel(isAutoGenerated: false)),
      );

      expect(find.text(kAutoGeneratedBadgeLabel), findsNothing);
    });

    // THE LOAD-BEARING CASE. A regenerate must never take away the model the
    // user already has.
    testWidgets('keeps the existing model viewable while a newer run is going',
        (tester) async {
      await _pump(
        tester,
        OwnerModelState(
          model: _finishedModel(),
          generation: const OwnerGenerationView(
            id: 'g2',
            status: ModelStatus.processing,
            isAutoGenerated: false,
          ),
        ),
      );

      expect(find.text('View 3D model'), findsOneWidget);
      expect(find.text('Creating your 3D model'), findsNothing);
      expect(find.textContaining('updated version'), findsOneWidget);
    });

    testWidgets('a failed generation offers Try again, never a raw error',
        (tester) async {
      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            projectsRepositoryProvider.overrideWithValue(
              _FakeRepo(
                const OwnerModelState(
                  generation: OwnerGenerationView(
                    id: 'g',
                    status: ModelStatus.failed,
                    isAutoGenerated: true,
                  ),
                ),
              ),
            ),
          ],
          child: MaterialApp(
            home: ModelBuildingScreen(
              projectId: 'p1',
              projectName: 'Chair',
              onRegenerate: () {},
            ),
          ),
        ),
      );
      await tester.pump();

      expect(find.text("We couldn't build your model"), findsOneWidget);
      expect(find.text('Try again'), findsOneWidget);
      // No code, no upstream text, nothing about the vendor.
      expect(find.textContaining('Meshy'), findsNothing);
    });

    testWidgets('empty state when there is no model and nothing running',
        (tester) async {
      await _pump(tester, const OwnerModelState());

      expect(find.text('No 3D model yet'), findsOneWidget);
    });
  });
}
